faqs_en = [
    {
        "category": "Basics",
        "faqs":[
            {
                "question":"What is a novel coronavirus?",
                "answer":"On February 11, 2020 the World Health Organization announced an official name for the disease that is causing the 2019 novel coronavirus outbreak, first identified in Wuhan China. The new name of this disease is coronavirus disease 2019, abbreviated as COVID-19. In COVID-19, ‘CO’ stands for ‘corona,’ ‘VI’ for ‘virus,’ and ‘D’ for disease. Formerly, this disease was referred to as \"2019 novel coronavirus\" or \"2019-nCoV\".\n\nA novel coronavirus is a new coronavirus that has not been previously identified. The virus causing coronavirus disease 2019 (COVID-19), is not the same as the coronaviruses that commonly circulate among humans and cause mild illness, like the common cold."
            },
            {
                "question":"Why is the disease being called corona virus disease 2019, COVID-19?",
                "answer": "There are many types of human corona viruses including some that commonly cause mild upper-respiratory tract illnesses. COVID-19 is a new disease, caused by a novel (or new) coronavirus that has not previously been seen in humans. The name of this disease was selected following the World Health Organization (WHO) best practice external icon for naming of new human infectious diseases."
            },
            {
                "question":"How can people help stop stigma related to COVID-19?",
                "answer":"People can fight stigma and help, not hurt, others by providing social support. Counter stigma by learning and sharing facts. Communicating the facts that viruses do not target specific racial or ethnic groups and how COVID-19 actually spreads can help stop stigma."
            }
        ]
    },
    {
        "category": "How It Spreads",
        "faqs":[
            {
                "question":"What is the source of the virus?",
                "answer": "Coronaviruses are a large family of viruses. Some cause illness in people, and others, such as canine and feline coronaviruses, only infect animals. Rarely, animal coronaviruses that infect animals have emerged to infect people and can spread between people. This is suspected to have occurred for the virus that causes COVID-19. Middle East Respiratory Syndrome (MERS) and Severe Acute Respiratory Syndrome (SARS) are two other examples of coronaviruses that originated from animals and then spread to people."
            },
            {
                "question":"How does the virus spread?",
                "answer":"This virus was first detected in Wuhan City, Hubei Province, China. The first infections were linked to a live animal market, but the virus is now spreading from person-to-person. It’s important to note that person-to-person spread can happen on a continuum. Some viruses are highly contagious (like measles), while other viruses are less so.\n\nThe virus that causes COVID-19 seems to be spreading easily and sustainably in the community (\"community spread\") in some affected geographic areas. Community spread means people have been infected with the virus in an area, including some who are not sure how or where they became infected."
            },
            {
                "question":"Can someone who has had COVID-19 spread the illness to others?",
                "answer":"The virus that causes COVID-19 is spreading from person-to-person. Someone who is actively sick with COVID-19 can spread the illness to others. That is why CDC recommends that these patients be isolated either in the hospital or at home (depending on how sick they are) until they are better and no longer pose a risk of infecting others.\n\nHow long someone is actively sick can vary so the decision on when to release someone from isolation is made on a case-by-case basis in consultation with doctors, infection prevention and control experts, and public health officials and involves considering specifics of each situation including disease severity, illness signs and symptoms, and results of laboratory testing for that patient.\n\nCurrent CDC guidance for when it is OK to release someone from isolation is made on a case by case basis and includes meeting all of the following requirements:\n\nThe patient is free from fever without the use of fever-reducing medications.\nThe patient is no longer showing symptoms, including cough.\nThe patient has tested negative on at least two consecutive respiratory specimens collected at least 24 hours apart.\nSomeone who has been released from isolation is not considered to pose a risk of infection to others."
            },
            {
                "question":"Will warm weather stop the outbreak of COVID-19?",
                "answer":"It is not yet known whether weather and temperature impact the spread of COVID-19. Some other viruses, like the common cold and flu, spread more during cold weather months but that does not mean it is impossible to become sick with these viruses during other months. At this time, it is not known whether the spread of COVID-19 will decrease when weather becomes warmer. There is much more to learn about the transmissibility, severity, and other features associated with COVID-19 and investigations are ongoing."
            },
            {
                "question":"Can the virus that causes COVID-19 be spread through food, including refrigerated or frozen food?",
                "answer":"Coronaviruses are generally thought to be spread from person-to-person through respiratory droplets. Currently there is no evidence to support transmission of COVID-19 associated with food. Before preparing or eating food it is important to always wash your hands with soap and water for 20 seconds for general food safety. Throughout the day wash your hands after blowing your nose, coughing or sneezing, or going to the bathroom.\n\nIt may be possible that a person can get COVID-19 by touching a surface or object that has the virus on it and then touching their own mouth, nose, or possibly their eyes, but this is not thought to be the main way the virus spreads.\n\nIn general, because of poor survivability of these coronaviruses on surfaces, there is likely very low risk of spread from food products or packaging that are shipped over a period of days or weeks at ambient, refrigerated, or frozen temperatures."
            },
            {
                "question":"What is community spread?",
                "answer":"Community spread means people have been infected with the virus in an area, including some who are not sure how or where they became infected.\n\nIn other words it becomes impossible to detect the source of infection and how much it has spread."
            }
        ]
    },
    {
        "category":"How to Protect Yourself",
        "faqs":[
            {
                "question":"Who is at higher risk for serious illness from COVID-19?",
                "answer":"Older adults and people of any age who have serious underlying medical conditions may be at higher risk for more serious complications from COVID-19. These people who may be at higher risk of getting very sick from this illness, includes:\n\nOlder adults\nPeople who have serious underlying medical conditions like:\n\t\tHeart disease\n\t\tDiabetes\n\t\tLung disease"
            },
            {
                "question":"What should people at higher risk of serious illness with COVID-19 do?",
                "answer":"If you are at higher risk of getting very sick from COVID-19, you should: stock up on supplies; take everyday precautions to keep space between yourself and others; when you go out in public, keep away from others who are sick; limit close contact and wash your hands often; and avoid crowds, cruise travel, and non-essential travel. If there is an outbreak in your community, stay home as much as possible. Watch for symptoms and emergency signs. If you get sick, stay home and call your doctor"
            },
            {
                "question":"Should I wear a mask to protect myself?",
                "answer":"Only wear a mask if you are ill with COVID-19 symptoms (especially coughing) or looking after someone who may have COVID-19. Disposable face mask can only be used once. If you are not ill or looking after someone who is ill then you are wasting a mask. There is a world-wide shortage of masks, so WHO urges people to use masks wisely.\n\nWHO advises rational use of medical masks to avoid unnecessary wastage of precious resources and mis-use of masks\n\nThe most effective ways to protect yourself and others against COVID-19 are to frequently clean your hands, cover your cough with the bend of elbow or tissue and maintain a distance of at least 1 meter (3 feet) from people who are coughing or sneezing. See basic protective measures against the new coronavirus for more information."
            }
        ]
    },
    {
        "category":"Symptoms & Testing",
        "faqs":[
            {
                "question":"Should I be tested for COVID-19?",
                "answer":"Not everyone needs to be tested for COVID-19. Only those who show major symptoms should get tested."
            },
            {
                "question":"Where can I get tested for COVID-19?",
                "answer":"The process and locations for testing vary from place to place. Contact your state, local, tribal, or territorial department for more information, or reach out to a medical provider. State and local public health departments have received tests from CDC while medical providers are getting tests developed by commercial manufacturers. While supplies of these tests are increasing, it may still be difficult to find someplace to get tested.\n\nSome COVID-19 tessting labs information is given in the resources section of the app"
            },
            {
                "question":"Can a person test negative and later test positive for COVID-19?",
                "answer":"Using the CDC-developed diagnostic test, a negative result means that the virus that causes COVID-19 was not found in the person’s sample. In the early stages of infection, it is possible the virus will not be detected.\n\nFor COVID-19, a negative test result for a sample collected while a person has symptoms likely means that the COVID-19 virus is not causing their current illness."
            }
        ]
    },
    {
        "category":"Outbreak in Your Community",
        "faqs":[
            {
                "question":"What should I do if there is an outbreak in my community?",
                "answer":"During an outbreak, stay calm and put your preparedness plan to work. Follow the steps below:\n\nProtect yourself and others.\n\n\t\tStay home if you are sick. Keep away from people who are sick. Limit close contact with others as much as possible (about 6 feet).\n\nPut your household plan into action.\n\n\t\tStay informed about the local COVID-19 situation. Be aware of temporary school dismissals in your area, as this may affect your household’s daily routine.\n\n\t\tContinue practicing everyday preventive actions. Cover coughs and sneezes with a tissue and wash your hands often with soap and water for at least 20 seconds. If soap and water are not available, use a hand sanitizer that contains 60% alcohol. Clean frequently touched surfaces and objects daily using a regular household detergent and water.\n\n\t\tNotify your workplace as soon as possible if your regular work schedule changes. Ask to work from home or take leave if you or someone in your household gets sick with COVID-19 symptoms, or if your child’s school is dismissed temporarily.\n\n\t\tStay in touch with others by phone or email. If you have a chronic medical condition and live alone, ask family, friends, and health care providers to check on you during an outbreak. Stay in touch with family and friends, especially those at increased risk of developing severe illness, such as older adults and people with severe chronic medical conditions."
            },
            {
                "question":"How do I prepare my children in case of COVID-19 outbreak in our community?",
                "answer":"Outbreaks can be stressful for adults and children. Talk with your children about the outbreak, try to stay calm, and reassure them that they are safe. If appropriate, explain to them that most illness from COVID-19 seems to be mild."
            },
            {
                "question":"What steps should parents take to protect children during a community outbreak?",
                "answer":"This is a new virus and we are still learning about it, but so far, there does not seem to be a lot of illness in children. Most illness, including serious illness, is happening in adults of working age and older adults. If there are cases of COVID-19 that impact your child’s school, the school may dismiss students. Keep track of school dismissals in your community. Read or watch local media sources that report school dismissals. If schools are dismissed temporarily, use alternative childcare arrangements, if needed.\n\nIf your child/children become sick with COVID-19, notify their childcare facility or school. Talk with teachers about classroom assignments and activities they can do from home to keep up with their schoolwork.\n\nDiscourage children and teens from gathering in other public places while school is dismissed to help slow the spread of COVID-19 in the community."
            },
            {
                "question":"Should I go to work if there is an outbreak in my community?",
                "answer":"Follow the advice of your local health officials. Stay home if you can. Talk to your employer to discuss working from home, taking leave if you or someone in your household gets sick with COVID-19 symptoms, or if your child’s school is dismissed temporarily. Employers should be aware that more employees may need to stay at home to care for sick children or other sick family members than is usual in case of a community outbreak."
            }
        ]
    },
    {
        "category":"Myth-Busters of coronavirus",
        "faqs":[
            {
                "question":"COVID-19 virus can be transmitted in areas with hot and humid climates?",
                "answer":"From the evidence so far, the COVID-19 virus can be transmitted in ALL AREAS, including areas with hot and humid weather. Regardless of climate, adopt protective measures if you live in, or travel to an area reporting COVID-19. The best way to protect yourself against COVID-19 is by frequently cleaning your hands. By doing this you eliminate viruses that may be on your hands and avoid infection that could occur by then touching your eyes, mouth, and nose."
            },
            {
                "question":"Cold weather and snow CANNOT kill the new coronavirus",
                "answer":"There is no reason to believe that cold weather can kill the new coronavirus or other diseases. The normal human body temperature remains around 36.5°C to 37°C, regardless of the external temperature or weather. The most effective way to protect yourself against the new coronavirus is by frequently cleaning your hands with alcohol-based hand rub or washing them with soap and water."
            },
            {
                "question":"Taking a hot bath does not prevent the new coronavirus disease",
                "answer":"Taking a hot bath will not prevent you from catching COVID-19. Your normal body temperature remains around 36.5°C to 37°C, regardless of the temperature of your bath or shower. Actually, taking a hot bath with extremely hot water can be harmful, as it can burn you. The best way to protect yourself against COVID-19 is by frequently cleaning your hands. By doing this you eliminate viruses that may be on your hands and avoid infection that could occur by then touching your eyes, mouth, and nose."
            },
            {
                "question":"The new coronavirus CANNOT be transmitted through mosquito bites.",
                "answer":"To date there has been no information nor evidence to suggest that the new coronavirus could be transmitted by mosquitoes. The new coronavirus is a respiratory virus which spreads primarily through droplets generated when an infected person coughs or sneezes, or through droplets of saliva or discharge from the nose. To protect yourself, clean your hands frequently with an alcohol-based hand rub or wash them with soap and water. Also, avoid close contact with anyone who is coughing and sneezing."
            },
            {
                "question":"Are hand dryers effective in killing the new coronavirus?",
                "answer":"No. Hand dryers are not effective in killing the 2019-nCoV. To protect yourself against the new coronavirus, you should frequently clean your hands with an alcohol-based hand rub or wash them with soap and water. Once your hands are cleaned, you should dry them thoroughly by using paper towels or a warm air dryer."
            },
            {
                "question":"Can an ultraviolet disinfection lamp kill the new coronavirus?",
                "answer":"UV lamps should not be used to sterilize hands or other areas of skin as UV radiation can cause skin irritation."
            },
            {
                "question":"How effective are thermal scanners in detecting people infected with the new coronavirus?",
                "answer":"Thermal scanners are effective in detecting people who have developed a fever (i.e. have a higher than normal body temperature) because of infection with the new coronavirus.\n\nHowever, they cannot detect people who are infected but are not yet sick with fever. This is because it takes between 2 and 10 days before people who are infected become sick and develop a fever."
            },
            {
                "question":"Do vaccines against pneumonia protect you against the new coronavirus?",
                "answer":"No. Vaccines against pneumonia, such as pneumococcal vaccine and Haemophilus influenza type B (Hib) vaccine, do not provide protection against the new coronavirus.\n\nThe virus is so new and different that it needs its own vaccine. Researchers are trying to develop a vaccine against 2019-nCoV, and WHO is supporting their efforts.\n\nAlthough these vaccines are not effective against 2019-nCoV, vaccination against respiratory illnesses is highly recommended to protect your health."
            }
        ]
    }
]

faqs_hi = [
    {
        "category": "कोरोनावायरस रोग मूल बातें",
        "faqs":[
            {
                "question":"एक नोवेल कोरोनोवायरस क्या है?",
                "answer":"11 फरवरी, 2020 को विश्व स्वास्थ्य संगठन ने इस बीमारी के लिए एक आधिकारिक नाम की घोषणा की, जो 2019 के नोवेल कोरोनावायरस के प्रकोप का कारण बन रहा है, जिसे पहले वुहान, चीन में पहचाना गया था। इस बीमारी का नया नाम कोरोनावायरस रोग 2019 है, जिसे COVID-19 कहा जाता है। COVID-19 में, 'CO' का अर्थ कोरोना, 'VI' के लिए वायरस और बीमारी के लिए 'D' है। पूर्व में, इस बीमारी को \"2019 नोवेल कोरोनवायरस\" या \"2019-n-COV \" के रूप में संदर्भित किया गया था। \n\nनोवेल कोरोनावायरस एक नया कोरोनोवायरस है जिसे पहले नहीं पहचाना गया है। कोरोनवायरस वायरस 2019 (COVID-19) पैदा करने वाला वायरस, कोरोनवीरस के समान नहीं है जो आम तौर पर मनुष्यों में फैलता है और आम सर्दी की तरह हल्के बीमारी का कारण बनता है।"
            },
            {
                "question":"बीमारी को कोरोना वायरस रोग 2019, COVID-19 क्यों कहा जा रहा है?",
                "answer": "मानव कोरोना वायरस कई प्रकार के होते हैं, जिनमें से कुछ सामान्य रूप से हल्के ऊपरी श्वसन तंत्र की बीमारियों का कारण बनते हैं। COVID-19 एक नई बीमारी है, जो एक उपन्यास (या नए) कोरोनावायरस के कारण होती है जो पहले मनुष्यों में नहीं देखी गई थी। विश्व स्वास्थ्य संगठन (डब्ल्यूएचओ) द्वारा नए मानव संक्रामक रोगों के नामकरण के लिए सबसे अच्छा अभ्यास बाहरी आइकन के बाद इस बीमारी का नाम चुना गया था।"
            },
            {
                "question":"COVID-19 से जुड़े कलंक को रोकने में लोग कैसे मदद कर सकते हैं?",
                "answer":"लोग कलंक से लड़ सकते हैं और मदद कर सकते हैं, चोट नहीं, दूसरों को सामाजिक सहायता प्रदान करके। तथ्यों को सीखने और साझा करने से काउंटर कलंक। इस तथ्य का संचार करना कि वायरस विशिष्ट नस्लीय या जातीय समूहों को लक्षित नहीं करते हैं और COVID-19 वास्तव में कैसे फैलता है, कलंक को रोकने में मदद कर सकता है।"
            }
        ]
    },
    {
        "category": "यह कैसे फैलता है",
        "faqs":[
            {
                "question":"वायरस का स्रोत क्या है?",
                "answer": "कोरोनावीरस वायरस का एक बड़ा परिवार है। कुछ लोगों में बीमारी का कारण बनता है, और अन्य, जैसे कि कुत्ते और बिल्ली के समान कोरोनवीरस, केवल जानवरों को संक्रमित करते हैं। दुर्लभ रूप से, पशु कोरोनविर्यूज़ कहते हैं कि संक्रमित जानवर लोगों को संक्रमित करने के लिए उभरे हैं और लोगों के बीच फैल सकते हैं। यह वायरस के लिए होने का संदेह है जो COVID-19 का कारण बनता है। मध्य पूर्व श्वसन सिंड्रोम (MERS) और गंभीर तीव्र श्वसन सिंड्रोम (SARS) कोरोनवीर के दो अन्य उदाहरण हैं जो जानवरों से उत्पन्न हुए और फिर लोगों में फैल गए।"
            },
            {
                "question":"वायरस कैसे फैलता है?",
                "answer":"इस वायरस का पहली बार पता चीन के हुबेई प्रांत के वुहान शहर में लगा था। पहले संक्रमण एक जीवित पशु बाजार से जुड़े थे, लेकिन वायरस अब व्यक्ति-से-व्यक्ति तक फैल रहा है। यह ध्यान रखना महत्वपूर्ण है कि व्यक्ति-से-व्यक्ति प्रसार एक सातत्य पर हो सकता है। कुछ वायरस अत्यधिक संक्रामक होते हैं (जैसे खसरा), जबकि अन्य वायरस कम होते हैं। कुछ प्रभावित भौगोलिक क्षेत्रों में COVID-19 के कारण वायरस आसानी से और निरंतर रूप से फैल रहा है। । सामुदायिक प्रसार का मतलब है कि लोग किसी क्षेत्र में वायरस से संक्रमित हो गए हैं, जिनमें कुछ ऐसे भी हैं जो यह सुनिश्चित नहीं कर रहे हैं कि वे कैसे या कहाँ संक्रमित हो गए।"
            },
            {
                "question":"क्या कोई व्यक्ति जिसे COVID-19 है, वह बीमारी दूसरों को फैला सकता है?",
                "answer":"COVID​​-19 का कारण बनने वाला वायरस व्यक्ति-से-व्यक्ति में फैल रहा है। कोई है जो COVID-19 के साथ सक्रिय रूप से बीमार है, दूसरों को बीमारी फैला सकता है। इसीलिए CDC की सलाह है कि इन रोगियों को या तो अस्पताल या घर पर अलग-थलग किया जाए (वे कितने बीमार हैं) पर निर्भर करता है जब तक कि वे बेहतर हैं और अब दूसरों को संक्रमित करने का जोखिम नहीं उठाते।\n\nजब तक कोई व्यक्ति सक्रिय रूप से बीमार हो सकता है तब तक भिन्न हो सकते हैं। इसलिए जब किसी को अलगाव से मुक्त करने का निर्णय डॉक्टरों, संक्रमण की रोकथाम और नियंत्रण विशेषज्ञों और सार्वजनिक स्वास्थ्य अधिकारियों के परामर्श से मामले-दर-मामला आधार पर किया जाता है और इसमें रोग की गंभीरता, बीमारी के संकेत और लक्षण सहित प्रत्येक स्थिति की बारीकियों पर विचार करना शामिल होता है, और उस रोगी के लिए प्रयोगशाला परीक्षण के परिणाम।\n\nसीडीसी मार्गदर्शन के मुताबिक, अलगाव से किसी को मुक्त करना ठीक है यह केस-दर-केस के आधार पर किया जाता है और इसमें निम्नलिखित सभी आवश्यकताओं को पूरा करना शामिल होता है:\n\nरोगी मुक्त होता है बुखार से बिना बुखार कम करने वाली दवाओं के उपयोग के।\nरोगी अब खांसी सहित लक्षण नहीं दिखा रहा है।\nरोगी ने कम से कम दो लगातार वायरस नमूनों को कम से कम एकत्र करने पर नकारात्मक परीक्षण किया है, 24 घंटे के अंदर।\nजो किसी अलगाव से मुक्त हुए हैं, उन्हें दूसरों को संक्रमण का खतरा नहीं माना जाता है।"
            },
            {
                "question":"क्या गर्म मौसम COVID-19 के प्रकोप को रोक देगा?",
                "answer":"यह अभी तक ज्ञात नहीं है कि मौसम और तापमान COVID-19 के प्रसार को प्रभावित करते हैं या नहीं। आम सर्दी और फ्लू जैसे कुछ अन्य वायरस ठंड के मौसम के महीनों में अधिक फैलते हैं लेकिन इसका मतलब यह नहीं है कि अन्य महीनों के दौरान इन वायरस से बीमार होना असंभव है। इस समय, यह ज्ञात नहीं है कि मौसम गर्म होने पर COVID-19 का प्रसार कम हो जाएगा या नहीं। COVID-19 के साथ संचार, गंभीरता, और अन्य सुविधाओं के बारे में जानने के लिए बहुत कुछ है और जांच जारी है।"
            },
            {
                "question":"क्या COVID-19 का कारण बनने वाला वायरस प्रशीतित या जमे हुए भोजन सहित भोजन के माध्यम से फैल सकता है?",
                "answer":"आमतौर पर कोरोनवीर को श्वसन बूंदों के माध्यम से व्यक्ति-से-व्यक्ति में फैलाने के लिए माना जाता है। वर्तमान में भोजन से जुड़े COVID-19 के प्रसारण का समर्थन करने के लिए कोई सबूत नहीं है। भोजन तैयार करने या खाने से पहले सामान्य खाद्य सुरक्षा के लिए हमेशा अपने हाथों को साबुन और पानी से 20 सेकंड तक धोना जरूरी है। दिन भर में अपनी नाक बहने, खांसने या छींकने या बाथरूम जाने के बाद अपने हाथ धोएं।\n\nयह संभव हो सकता है कि कोई व्यक्ति किसी सतह या वस्तु को छूकर उस पर वायरस का निशान लगाकर COVID-19 प्राप्त कर सकता है और फिर अपने स्वयं के मुंह, नाक, या संभवतः उनकी आंखों को छू सकता है, लेकिन यह वायरस का मुख्य तरीका नहीं माना जाता है फैलता है।\n\nसामान्य तौर पर, सतहों पर इन कोरोनविर्यूज़ के खराब अस्तित्व के कारण, खाद्य उत्पादों या पैकेजिंग से फैलने की संभावना बहुत कम होती है, जो परिवेश, प्रशीतित या जमे हुए तापमान पर दिनों या हफ्तों की अवधि में भेज दी जाती है।"
            },
            {
                "question":"सामुदायिक प्रसार क्या है?",
                "answer":"सामुदायिक प्रसार का अर्थ है कि लोग किसी क्षेत्र में वायरस से संक्रमित हो गए हैं, जिनमें कुछ ऐसे भी हैं जो सुनिश्चित नहीं हैं कि वे कैसे या कहाँ संक्रमित हो गए।\n\nदूसरे शब्दों में यह संक्रमण के स्रोत और यह कितना फैल गया है, यह पता लगाना असंभव है।"
            }
        ]
    },
    {
        "category":"खुद की सुरक्षा कैसे करें",
        "faqs":[
            {
                "question":"COVID-19 से गंभीर बीमारी के लिए कौन अधिक जोखिम में है?",
                "answer":"पुराने वयस्क और किसी भी आयु के लोग जिनके पास गंभीर अंतर्निहित चिकित्सा स्थितियां हैं, COVID-19 से अधिक गंभीर जटिलताओं के लिए उच्च जोखिम में हो सकते हैं। इन लोगों को जो इस बीमारी से बहुत बीमार होने का खतरा हो सकता है, में शामिल हैं:\n\t\tदिल की बीमारी\n\t\tमधुमेह\n\t\tफेफड़ों की बीमारी"
            },
            {
                "question":"COVID-19 के साथ गंभीर बीमारी के उच्च जोखिम वाले लोगों को क्या करना चाहिए?",
                "answer":"यदि आपको COVID-19 से बहुत बीमार होने का खतरा है, तो आपको चाहिए: आपूर्ति पर स्टॉक; अपने और दूसरों के बीच स्थान रखने के लिए रोज़मर्रा की सावधानियां बरतें; जब आप सार्वजनिक रूप से बाहर जाते हैं, तो दूसरों से दूर रहें जो बीमार हैं; निकट संपर्क सीमित करें और अपने हाथों को अक्सर धोएं; और भीड़, क्रूज यात्रा और गैर-आवश्यक यात्रा से बचें। यदि आपके समुदाय में इसका प्रकोप है, तो जितना संभव हो सके घर में रहें। लक्षण और आपातकालीन संकेतों के लिए देखें। यदि आप बीमार हो जाते हैं, तो घर पर रहें और अपने डॉक्टर को बुलाएं"
            },
            {
                "question":"क्या मुझे अपनी सुरक्षा के लिए मास्क पहनना चाहिए?",
                "answer":"यदि आप COVID-19 लक्षणों (विशेष रूप से खाँसी) के साथ बीमार हैं या किसी ऐसे व्यक्ति की देखभाल कर रहे हैं जो COVID -19 हो तो केवल मास्क पहनें। डिस्पोजेबल फेस मास्क का उपयोग केवल एक बार किया जा सकता है। यदि आप बीमार नहीं हैं या किसी ऐसे व्यक्ति की तलाश कर रहे हैं जो बीमार है तो आप एक मुखौटा बर्बाद कर रहे हैं। मास्क की दुनिया भर में कमी है, इसलिए विश्‍व स्वास्थ्‍य संगटन लोगों से बुद्धिमानी से मास्क का उपयोग करने का आग्रह करता है। कीमती संसाधनों के अनावश्यक अपव्यय से बचने और मास्क के\n\nके गलत उपयोग से बचने के लिए मेडिकल मास्क के तर्कसंगत उपयोग की सलाह देता है। स्वयं को और दूसरों को सीओवीआईडी -19 से बचाएं, अपने हाथों को बार-बार साफ करना है, अपनी खांसी को कोहनी या ऊतक के मोड़ से ढकें और खांसने या छींकने वाले लोगों से कम से कम 1 मीटर (3 फीट) की दूरी बनाए रखें। अधिक जानकारी के लिए नए कोरोनावायरस के खिलाफ बुनियादी सुरक्षात्मक उपाय देखें।"
            }
        ]
    },
    {
        "category":"लक्षण और परीक्षण",
        "faqs":[
            {
                "question":"क्या मुझे COVID-19 का परीक्षण करना चाहिए?",
                "answer":"सभी को COVID-19 के परीक्षण की आवश्यकता नहीं है। केवल जो प्रमुख लक्षण दिखाते हैं, उन्हें परीक्षण करवाना चाहिए।"
            },
            {
                "question":"मुझे COVID-19 के लिए परीक्षण कहां मिल सकता है?",
                "answer":"परीक्षण के लिए प्रक्रिया और स्थान अलग-अलग हैं। अधिक जानकारी के लिए अपने राज्य, स्थानीय, आदिवासी, या क्षेत्रीय विभाग से संपर्क करें, या एक चिकित्सा प्रदाता तक पहुंचें। राज्य और स्थानीय सार्वजनिक स्वास्थ्य विभागों ने सीडीसी से परीक्षण प्राप्त किए हैं, जबकि चिकित्सा प्रदाताओं को वाणिज्यिक निर्माताओं द्वारा विकसित परीक्षण प्राप्त हो रहे हैं। हालांकि इन परीक्षणों की आपूर्ति बढ़ रही है, फिर भी परीक्षण करने के लिए कुछ जगह ढूंढना मुश्किल हो सकता है।\n\nकुछ COVID-19 परीक्षण प्रयोगशालाओं की जानकारी ऐप के संसाधन अनुभाग में दी गई है।"
            },
            {
                "question":"क्या कोई व्यक्ति नकारात्मक परीक्षण कर सकता है और बाद में COVID-19 के लिए सकारात्मक परीक्षण कर सकता है?",
                "answer":"सीडीसी-विकसित नैदानिक परीक्षण का उपयोग करते हुए, एक नकारात्मक परिणाम का अर्थ है कि वायरस जो COVID-19 का कारण बनता है वह व्यक्ति के नमूने में नहीं पाया गया था। संक्रमण के शुरुआती चरणों में, यह संभव है कि वायरस का पता नहीं चलेगा।\n\nCOVID -19 के लिए, एक नमूने के लिए एक नकारात्मक परीक्षण परिणाम एकत्र किया जाता है, जबकि किसी व्यक्ति में लक्षण होने का मतलब है कि COVID-19 वायरस उनकी वर्तमान बीमारी का कारण नहीं है।"
            }
        ]
    },
    {
        "category":"अपने समुदाय में प्रकोप",
        "faqs":[
            {
                "question":"अगर मेरे समुदाय में इसका प्रकोप है तो मुझे क्या करना चाहिए?",
                "answer":"प्रकोप के दौरान, शांत रहें और अपनी तैयारियों की योजना पर काम करें। नीचे दिए गए चरणों का पालन करें:\n\nअपनी और दूसरों की रक्षा करें।\n\nअगर आप बीमार हैं तो घर पर रहें। ऐसे लोगों से दूर रहें जो बीमार हैं। जितना संभव हो दूसरों के साथ निकट संपर्क सीमित करें (लगभग 6 फीट)।\n\nअपनी घरेलू योजना को अमल में लाएं।\n\n\t\tस्थानीय COVID-19 स्थिति के बारे में सूचित रहें। अपने क्षेत्र में अस्थायी स्कूल बर्खास्तगी से अवगत रहें, क्योंकि इससे आपके घर की दिनचर्या प्रभावित हो सकती है।\n\nप्रतिदिन निवारक क्रियाओं का अभ्यास जारी रखें। खांसी और छींक को एक ऊतक के साथ कवर करें और कम से कम 20 सेकंड के लिए अपने हाथों को अक्सर साबुन और पानी से धोएं। यदि साबुन और पानी उपलब्ध नहीं है, तो एक हाथ प्रक्षालक का उपयोग करें जिसमें 60% एलकोहॉल हो। एक नियमित रूप से घरेलू डिटर्जेंट और पानी का उपयोग करके दैनिक रूप से छुआ सतहों और वस्तुओं को साफ करें।\n\nयदि आपके नियमित कार्य शेड्यूल में परिवर्तन होता है, तो जल्द से जल्द अपने कार्यस्थल को सूचित करें। घर से काम करने या छुट्टी लेने के लिए कहें यदि आप या आपके घर में कोई व्यक्ति COVID-19 लक्षणों से बीमार हो जाता है, या यदि आपके बच्चे के स्कूल को अस्थायी रूप से खारिज कर दिया जाता है।\n\nफोन या ईमेल द्वारा दूसरों के संपर्क में रहें। यदि आपके पास एक पुरानी चिकित्सा स्थिति है और अकेले रहते हैं, तो प्रकोप के दौरान परिवार, दोस्तों और स्वास्थ्य देखभाल प्रदाताओं से आप पर जाँच करने के लिए कहें। परिवार और दोस्तों के साथ संपर्क में रहें, विशेष रूप से गंभीर बीमारी के बढ़ने के जोखिम में, जैसे कि वृद्ध वयस्कों और गंभीर पुरानी चिकित्सा स्थितियों वाले लोग।"
            },
            {
                "question":"हमारे समुदाय में COVID-19 के प्रकोप के मामले में मैं अपने बच्चों को कैसे तैयार करूं?",
                "answer":"प्रकोप वयस्कों और बच्चों के लिए तनावपूर्ण हो सकता है। अपने बच्चों के साथ प्रकोप के बारे में बात करें, शांत रहने की कोशिश करें, और उन्हें आश्वस्त करें कि वे सुरक्षित हैं। यदि उपयुक्त हो, तो उन्हें समझाएं कि COVID-19 से अधिकांश बीमारी हल्की प्रतीत होती है।"
            },
            {
                "question":"समुदाय के प्रकोप के दौरान माता-पिता को बच्चों की सुरक्षा के लिए क्या कदम उठाने चाहिए?",
                "answer":"यह एक नया वायरस है और हम अभी भी इसके बारे में सीख रहे हैं, लेकिन अभी तक, बच्चों में बहुत अधिक बीमारी नहीं लगती है। अधिकांश बीमारी, गंभीर बीमारी सहित, कामकाजी उम्र के वयस्कों और बड़े वयस्कों में हो रही है। यदि COVID-19 के मामले हैं जो आपके बच्चे के स्कूल को प्रभावित करते हैं, तो स्कूल छात्रों को खारिज कर सकता है। अपने समुदाय में स्कूल की बर्खास्तगी पर नज़र रखें। स्थानीय मीडिया स्रोतों को पढ़ें या देखें जो स्कूल बर्खास्तगी की रिपोर्ट करते हैं। यदि स्कूल अस्थायी रूप से खारिज कर दिए जाते हैं, तो यदि आवश्यक हो तो वैकल्पिक चाइल्डकैअर व्यवस्था का उपयोग करें।\n\nयदि आपका बच्चा/बच्चे COVID-19 से बीमार हो जाते हैं, तो उनकी चाइल्डकैअर सुविधा या स्कूल को सूचित करें। शिक्षकों के साथ कक्षा असाइनमेंट और गतिविधियों के बारे में बात करें जो वे अपने स्कूलवर्क के साथ रखने के लिए घर से कर सकते हैं।\n\nबच्चों और किशोरों को अन्य सार्वजनिक स्थानों पर इकट्ठा होने से हतोत्साहित करें जबकि स्कूल समुदाय में COVID-19 के प्रसार को धीमा करने में मदद करने के लिए खारिज किया जाता है।"
            },
            {
                "question":"क्या मुझे अपने समुदाय में प्रकोप होने पर काम पर जाना चाहिए?",
                "answer":"अपने स्थानीय स्वास्थ्य अधिकारियों की सलाह का पालन करें। आप कर सकते हैं तो घर पर रहो। अपने नियोक्ता से घर से काम करने पर चर्चा करने के लिए बात करें, यदि आप या आपके घर का कोई व्यक्ति COVID-19 लक्षणों से बीमार हो जाता है, या यदि आपके बच्चे के स्कूल को अस्थायी रूप से खारिज कर दिया जाता है, तो छुट्टी ले लें। नियोक्ता को पता होना चाहिए कि समुदाय के प्रकोप के मामले में सामान्य बच्चों की तुलना में बीमार बच्चों या अन्य बीमार परिवार के सदस्यों की देखभाल के लिए अधिक कर्मचारियों को घर पर रहना पड़ सकता है।"
            }
        ]
    },
    {
        "category":"कोरोनोवायरस के मिथक-गुच्छे",
        "faqs":[
            {
                "question":"COVID-19 वायरस गर्म और आर्द्र जलवायु वाले क्षेत्रों में प्रेषित किया जा सकता है?",
                "answer":"अब तक के सबूतों से, COVID-19 वायरस को गर्म और आर्द्र मौसम वाले क्षेत्रों सहित सभी क्षेत्रों में प्रेषित किया जा सकता है। जलवायु के बावजूद, यदि आप रहते हैं, या COVID-19 की रिपोर्ट करने वाले क्षेत्र में जाते हैं, तो सुरक्षात्मक उपाय अपनाएं। COVID-19 के खिलाफ खुद को बचाने का सबसे अच्छा तरीका है अक्सर अपने हाथों की सफाई करना। ऐसा करने से आप अपने हाथों पर लगने वाले वायरस को खत्म कर सकते हैं और संक्रमण से बच सकते हैं जो तब तक आपकी आंखों, मुंह और नाक को छू सकता है।"
            },
            {
                "question":"ठंड के मौसम और बर्फ नए कोरोनावायरस को नहीं मार सकते",
                "answer":"यह मानने का कोई कारण नहीं है कि ठंड का मौसम नए कोरोनावायरस या अन्य बीमारियों को मार सकता है। बाहरी तापमान या मौसम की परवाह किए बिना, सामान्य मानव शरीर का तापमान लगभग 36.5 ° C से 37 ° C तक रहता है। नए कोरोनावायरस के खिलाफ खुद को बचाने के लिए सबसे प्रभावी तरीका शराब पर आधारित हाथ रगड़ना या साबुन और पानी से धोना है।"
            },
            {
                "question":"गर्म स्नान करने से नए कोरोनावायरस रोग की रोकथाम नहीं होती है",
                "answer":"गर्म स्नान करने से आप COVID-19 को पकड़ने से नहीं रोक पाएंगे। आपके स्नान या शॉवर के तापमान की परवाह किए बिना आपके शरीर का सामान्य तापमान लगभग 36.5 ° C से 37 ° C तक रहता है। दरअसल, बेहद गर्म पानी से नहाना हानिकारक हो सकता है, क्योंकि यह आपको जला सकता है। COVID-19 के खिलाफ खुद को बचाने का सबसे अच्छा तरीका है अक्सर अपने हाथों की सफाई करना। ऐसा करने से आप अपने हाथों पर लगने वाले वायरस को खत्म कर सकते हैं और संक्रमण से बच सकते हैं जो तब तक आपकी आंखों, मुंह और नाक को छू सकता है।"
            },
            {
                "question":"नए कोरोनावायरस को मच्छर के काटने के माध्यम से प्रेषित नहीं किया जा सकता है।",
                "answer":"आज तक इस बारे में कोई जानकारी नहीं मिली है और न ही यह सुझाव दिया गया है कि नए कोरोनोवायरस को मच्छरों द्वारा प्रेषित किया जा सकता है। नया कोरोनावायरस एक श्वसन वायरस है जो मुख्य रूप से उत्पन्न बूंदों के माध्यम से फैलता है जब एक संक्रमित व्यक्ति खांसी या छींकता है, या लार की बूंदों के माध्यम से या नाक से निर्वहन करता है। अपने आप को बचाने के लिए, अपने हाथों को बार-बार अल्कोहल-आधारित हाथ रगड़ कर साफ करें या साबुन और पानी से धोएं। इसके अलावा, खांसी और छींकने वाले किसी भी व्यक्ति के साथ निकट संपर्क से बचें।"
            },
            {
                "question":"क्या नए कोरोनोवायरस को मारने में हाथ सुखाने वाले प्रभावी हैं?",
                "answer":"नहीं, 2019-nCoV को मारने में हैंड ड्रायर्स कारगर नहीं हैं। नए कोरोनावायरस के खिलाफ खुद को बचाने के लिए, आपको अक्सर अपने हाथों को अल्कोहल-आधारित हाथ रगड़कर साफ करना चाहिए या उन्हें साबुन और पानी से धोना चाहिए। एक बार जब आपके हाथ साफ हो जाते हैं, तो आपको कागज़ के तौलिये या गर्म हवा के ड्रायर का उपयोग करके उन्हें अच्छी तरह से सुखाना चाहिए।"
            },
            {
                "question":"क्या एक पराबैंगनी कीटाणुशोधन दीपक नए कोरोनोवायरस को मार सकता है?",
                "answer":"यूवी लैंप का उपयोग हाथों या त्वचा के अन्य क्षेत्रों को निष्फल करने के लिए नहीं किया जाना चाहिए क्योंकि यूवी विकिरण त्वचा की जलन पैदा कर सकता है।"
            },
            {
                "question":"नए कोरोनावायरस से संक्रमित लोगों का पता लगाने में थर्मल स्कैनर कितने प्रभावी हैं?",
                "answer":"थर्मल स्कैनर्स उन लोगों का पता लगाने में प्रभावी होते हैं, जिन्होंने नए कोरोनोवायरस के संक्रमण के कारण बुखार (यानी शरीर के सामान्य तापमान से अधिक) को प्रभावित किया है।\n\nकोई भी व्यक्ति, वे ऐसे लोगों का पता नहीं लगा सकते हैं जो संक्रमित हैं, लेकिन बुखार से अभी तक बीमार नहीं हैं। ऐसा इसलिए है क्योंकि संक्रमित लोगों के बीमार होने और बुखार के विकसित होने से पहले 2 से 10 दिन लगते हैं।"
            },
            {
                "question":"क्या निमोनिया के खिलाफ टीके नए कोरोनावायरस के खिलाफ आपकी रक्षा करते हैं?",
                "answer":"नहीं, निमोनिया के खिलाफ टीके, जैसे न्यूमोकोकल वैक्सीन और हीमोफिलस इन्फ्लुएंजा टाइप बी (हिब) वैक्सीन, नए कोरोनोवायरस के खिलाफ सुरक्षा प्रदान नहीं करते हैं।\n\nवायरस इतना नया और अलग है कि उसे अपना वैक्सीन चाहिए। शोधकर्ता 2019-nCoV के खिलाफ एक टीका विकसित करने की कोशिश कर रहे हैं, और WHO उनके प्रयासों का समर्थन कर रहा है।\n\nफिर भी ये टीके 2019-nCoV के खिलाफ प्रभावी नहीं हैं, श्वसन रोगों के खिलाफ टीकाकरण आपके स्वास्थ्य की रक्षा के लिए अत्यधिक अनुशंसित है।"
            }
        ]
    }
]

states = [
    "State Unassigned",
    "Maharashtra",
    "Gujarat",
    "Delhi",
    "Rajasthan",
    "Madhya Pradesh",
    "Tamil Nadu",
    "Uttar Pradesh",
    "Telangana",
    "Andhra Pradesh",
    "West Bengal",
    "Karnataka",
    "Kerala",
    "and Kashmir",
    "Jammu & Kashmir",
    "Punjab",
    "Haryana",
    "Bihar",
    "Odisha",
    "Jharkhand",
    "Uttarakhand",
    "Himachal Pradesh",
    "Chhattisgarh",
    "Assam",
    "Chandigarh",
    "Nicobar Islands",
    "Andaman & Nicobar",
    "Ladakh",
    "Meghalaya",
    "Goa",
    "Puducherry",
    "Manipur",
    "Tripura",
    "Mizoram",
    "Arunachal Pradesh",
    "Sikkim",
    "Nagaland",
    "Nagar Haveli",
    "Diu",
    "and Diu",
    "Lakshadweep",
]

states_hindi = {
            "maharashtra": "महाराष्ट्र",
            "gujarat": "गुजरात",
            "delhi": "दिल्ली",
            "rajasthan": "राजस्थान",
            "madhya_pradesh": "मध्य प्रदेश",
            "tamil_nadu": "तमिलनाडु",
            "uttar_pradesh": "उत्तर प्रदेश",
            "telangana": "तेलंगाना",
            "andhra_pradesh": "आंध्र प्रदेश",
            "west_bengal": "पश्चिम बंगाल",
            "karnataka": "कर्नाटक",
            "kerala": "केरल",
            "and_kashmir": "जम्मू और कश्मीर",
            "jammu_&_kashmir": "जम्मू और कश्मीर",
            "punjab": "पंजाब",
            "haryana": "हरियाणा",
            "bihar": "बिहार",
            "odisha": "ओडिशा",
            "jharkhand": "झारखंड",
            "uttarakhand": "उत्तराखंड",
            "himachal_pradesh": "हिमाचल प्रदेश",
            "chhattisgarh": "छत्तीसगढ़",
            "assam": "असम",
            "chandigarh": "चंडीगढ़",
            "_nicobar_islands": "अंडमान व नोकोबार द्वीप समूह",
            "andaman_&_nicobar": "अंडमान व नोकोबार",
            "ladakh": "लद्दाख",
            "meghalaya": "मेघालय",
            "goa": "गोवा",
            "puducherry": "पुडुचेरी",
            "manipur": "मणिपुर",
            "tripura": "त्रिपुरा",
            "mizoram": "मिजोरम",
            "arunachal_pradesh": "अरुणाचल प्रदेश",
            "sikkim": "सिक्किम",
            "state_unassigned": "अप्रमाणित राज्य",
            "nagaland": "नगालैंड",
            "nagar_haveli": "दादरा और नगर हवेली",
            "and_diu": "दादरा और नगर हवेली और दमन और दीव",
            "diu": "दादरा और नगर हवेली और दमन और दीव",
            "lakshadweep": "लक्षद्वीप",
            "pan_india": "पैन इंडिया",
        }

state_codes = {
    "TT": "Total",
    "AN": "Andaman and Nicobar Islands",
    "AP": "Andhra Pradesh",
    "AR": "Arunachal Pradesh",
    "AS": "Assam",
    "BR": "Bihar",
    "CH": "Chandigarh",
    "CT": "Chhattisgarh",
    "DN": "Dadra and Nagar Haveli and Daman and Diu",
    "DL": "Delhi",
    "GA": "Goa",
    "GJ": "Gujarat",
    "HR": "Haryana",
    "HP": "Himachal Pradesh",
    "JK": "Jammu and Kashmir",
    "JH": "Jharkhand",
    "KA": "Karnataka",
    "KL": "Kerala",
    "LA": "Ladakh",
    "LD": "Lakshadweep",
    "MP": "Madhya Pradesh",
    "MH": "Maharashtra",
    "MN": "Manipur",
    "MZ": "Mizoram",
    "ML": "Meghalaya",
    "NL": "Nagaland",
    "OR": "Odisha",
    "PY": "Puducherry",
    "PB": "Punjab",
    "RJ": "Rajasthan",
    "SK": "Sikkim",
    "UN": "State Unassigned",
    "TN": "Tamil Nadu",
    "TG": "Telangana",
    "TR": "Tripura",
    "UP": "Uttar Pradesh",
    "UT": "Uttarakhand",
    "WB": "West Bengal"
}

iso3_codes = {
  "afghanistan":"AFG",
  "albania":"ALB",
  "algeria":"DZA",
  "american_samoa":"ASM",
  "andorra":"AND",
  "angola":"AGO",
  "anguilla":"AIA",
  "antarctica":"ATA",
  "antigua_and_barbuda":"ATG",
  "argentina":"ARG",
  "armenia":"ARM",
  "aruba":"ABW",
  "australia":"AUS",
  "austria":"AUT",
  "azerbaijan":"AZE",
  "bahamas":"BHS",
  "bahrain":"BHR",
  "bangladesh":"BGD",
  "barbados":"BRB",
  "belarus":"BLR",
  "belgium":"BEL",
  "belize":"BLZ",
  "benin":"BEN",
  "bermuda":"BMU",
  "bhutan":"BTN",
  "bolivia":"BOL",
  "bosnia_and_herzegovina":"BIH",
  "bosnia": "BIH",
  "botswana":"BWA",
  "bouvet_island":"BVT",
  "brazil":"BRA",
  "british_indian_ocean_territory":"IOT",
  "british_virgin_islands": "VGB",
  "brunei":"BRN",
  "bulgaria":"BGR",
  "burkina_faso":"BFA",
  "burundi":"BDI",
  "cabo_verde":"CPV",
  "cambodia":"KHM",
  "cameroon":"CMR",
  "canada":"CAN",
  "cape_verde":"CPV",
  "caribbean_netherlands": "BES",
  "cayman_islands":"CYM",
  "central_african_republic":"CAF",
  "chad":"TCD",
  "chile":"CHL",
  "china":"CHN",
  "channel_islands": "Channel Islands",
  "christmas_island":"CXR",
  "cocos_islands": "CCK",
  "cocos_(keeling)_islands":"CCK",
  "keeling": "CCK",
  "keeling_islands": "CCK",
  "colombia":"COL",
  "comoros":"COM",
  "congo":"COG",
  "the_democratic_republic_of_congo":"COD",
  "cook_islands":"COK",
  "costa_rica":"CRI",
  "côte_d'ivoire": "CIV",
  "curaçao": "CUW",
  "ivory_coast":"CIV",
  "croatia":"HRV",
  "cuba":"CUB",
  "cyprus":"CYP",
  "czech_republic":"CZE",
  "czechia": "CZE",
  "denmark":"DNK",
  "djibouti":"DJI",
  "dominica":"DMA",
  "dominican_republic":"DOM",
  "drc": "DRC",
  "east_timor":"TLS",
  "ecuador":"ECU",
  "egypt":"EGY",
  "england":"GBR",
  "el_salvador":"SLV",
  "equatorial_guinea":"GNQ",
  "eritrea":"ERI",
  "estonia":"EST",
  "ethiopia":"ETH",
  "falkland_islands":"FLK",
  "falkland_islands_(malvinas)":"FLK",
  "malvinas": "FLK",
  "malvinas_island": "FLK",
  "faroe_islands":"FRO",
  "fiji_islands":"FJI",
  "fiji": "FJI",
  "finland":"FIN",
  "france":"FRA",
  "french_guiana":"GUF",
  "french_polynesia":"PYF",
  "french_southern_territories":"ATF",
  "gabon":"GAB",
  "gambia":"GMB",
  "georgia":"GEO",
  "germany":"DEU",
  "ghana":"GHA",
  "gibraltar":"GIB",
  "greece":"GRC",
  "greenland":"GRL",
  "grenada":"GRD",
  "guadeloupe":"GLP",
  "guam":"GUM",
  "guatemala":"GTM",
  "guernsey":"GGY",
  "guinea":"GIN",
  "guinea-bissau":"GNB",
  "guyana":"GUY",
  "haiti":"HTI",
  "heard_island_and_mcdonald_islands":"HMD",
  "holy_see_(vatican_city_state)":"VAT",
  "vatican_city":"VAT",
  "honduras":"HND",
  "hong_kong":"HKG",
  "hungary":"HUN",
  "iceland":"ISL",
  "india":"IND",
  "indonesia":"IDN",
  "iran":"IRN",
  "iraq":"IRQ",
  "ireland":"IRL",
  "israel":"ISR",
  "isle_of_man":"IMN",
  "italy":"ITA",
  "jamaica":"JAM",
  "japan":"JPN",
  "jersey":"JEY",
  "jordan":"JOR",
  "kazakhstan":"KAZ",
  "kenya":"KEN",
  "kiribati":"KIR",
  "kuwait":"KWT",
  "kyrgyzstan":"KGZ",
  "lao_people's_democratic_republic": "LAO",
  "laos":"LAO",
  "latvia":"LVA",
  "lebanon":"LBN",
  "lesotho":"LSO",
  "liberia":"LBR",
  "libyan_arab_jamahiriya":"LBY",
  "liechtenstein":"LIE",
  "lithuania":"LTU",
  "luxembourg":"LUX",
  "macao":"MAC",
  "north_macedonia":"MKD",
  "macedonia": "MKD",
  "madagascar":"MDG",
  "malawi":"MWI",
  "malaysia":"MYS",
  "maldives":"MDV",
  "mali":"MLI",
  "malta":"MLT",
  "marshall_islands":"MHL",
  "martinique":"MTQ",
  "mauritania":"MRT",
  "mauritius":"MUS",
  "mayotte":"MYT",
  "mexico":"MEX",
  "micronesia,_federated_states_of":"FSM",
  "micronesia":"FSM",
  "federated_states_of_micronesia":"FSM",
  "moldova":"MDA",
  "monaco":"MCO",
  "mongolia":"MNG",
  "montenegro":"MNE",
  "montserrat":"MSR",
  "morocco":"MAR",
  "mozambique":"MOZ",
  "myanmar":"MMR",
  "namibia":"NAM",
  "nauru":"NRU",
  "nepal":"NPL",
  "netherlands":"NLD",
  "netherlands_antilles":"Netherlands Antilles",
  "new_caledonia":"NCL",
  "new_zealand":"NZL",
  "nicaragua":"NIC",
  "niger":"NER",
  "nigeria":"NGA",
  "niue":"NIU",
  "norfolk_island":"NFK",
  "north_korea":"PRK",
  "n._korea": "PRK",
  "northern_ireland":"GBR",
  "northern_mariana_islands":"MNP",
  "norway":"NOR",
  "oman":"OMN",
  "pakistan":"PAK",
  "palau":"PLW",
  "palestine":"PSE",
  "panama":"PAN",
  "papua_new_guinea":"PNG",
  "paraguay":"PRY",
  "peru":"PER",
  "philippines":"PHL",
  "pitcairn":"PCN",
  "poland":"POL",
  "portugal":"PRT",
  "puerto_rico":"PRI",
  "qatar":"QAT",
  "reunion":"REU",
  "réunion": "REU",
  "romania":"ROU",
  "russian_federation":"RUS",
  "russia": "RUS",
  "rwanda":"RWA",
  "st._barth": "St. Barth",
  "saint_martin": "MAF",
  "saint_helena":"SHN",
  "saint_kitts_and_nevis":"KNA",
  "saint_lucia":"LCA",
  "saint_pierre_and_miquelon":"SPM",
  "saint_pierre_miquelon":"SPM",
  "saint_vincent_and_the_grenadines":"VCT",
  "samoa":"WSM",
  "san_marino":"SMR",
  "sao_tome_and_principe":"STP",
  "saudi_arabia":"SAU",
  "scotland":"GBR",
  "senegal":"SEN",
  "serbia":"SRB",
  "seychelles":"SYC",
  "sierra_leone":"SLE",
  "singapore":"SGP",
  "sint_maarten": "SXM",
  "slovakia":"SVK",
  "slovenia":"SVN",
  "solomon_islands":"SLB",
  "somalia":"SOM",
  "south_africa":"ZAF",
  "south_georgia_and_the_south_sandwich_islands":"SGS",
  "south_korea":"KOR",
  "s._korea": "KOR",
  "south_sudan":"SSD",
  "spain":"ESP",
  "sri_lanka":"LKA",
  "sudan":"SDN",
  "suriname":"SUR",
  "svalbard_and_jan_mayen":"SJM",
  "swaziland":"SWZ",
  "eswatini":"SWZ",
  "sweden":"SWE",
  "switzerland":"CHE",
  "syria":"Syria",
  "syrian_arab_republic": "SYR",
  "taiwan": "TWN",
  "tajikistan":"TJK",
  "tanzania":"TZA",
  "thailand":"THA",
  "timor-leste":"TLS",
  "togo":"TGO",
  "tokelau":"TKL",
  "tonga":"TON",
  "trinidad_and_tobago":"TTO",
  "tunisia":"TUN",
  "turkey":"TUR",
  "turkmenistan":"TKM",
  "turks_and_caicos_islands":"TCA",
  "tuvalu":"TUV",
  "uganda":"UGA",
  "ukraine":"UKR",
  "united_arab_emirates":"ARE",
  "uae": "ARE",
  "united_kingdom":"GBR",
  "uk": "GBR",
  "united_states":"USA",
  "united_states_of_america": "USA",
  "usa": "USA",
  "united_states_minor_outlying_islands":"UMI",
  "uruguay":"URY",
  "uzbekistan":"UZB",
  "vanuatu":"VUT",
  "venezuela":"VEN",
  "vietnam":"VNM",
  "virgin_islands,_british":"VGB",
  "virgin_islands,_u.s.":"VIR",
  "virgin_islands":"VIR",
  "virgin_islands_u.s":"VIR",
  "virgin_islands_british":"VGB",
  "wales":"GBR",
  "wallis_and_futuna":"WLF",
  "western_sahara":"ESH",
  "yemen":"YEM",
  "yugoslavia":"Yugoslavia",
  "zambia":"ZMB",
  "zimbabwe":"ZWE"
}

states_and_districts = {
    "unknown": "अज्ञात",
    "italians": "इटली निवासी",
    "other_states": "अन्य राज्यों से",
    "other_state": "अन्य राज्यों से",
    "evacuees": "विस्थापित व्यक्ति",
    "foreign_evacuees": "विदेशी निकासी",
    "other_region": "अन्य क्षेत्र से",
    "bsf_camp": "बीएसएफ कैंप",
    "airport_quarantine": "हवाई अड्डा संगरोध",
    "state_unassigned": "अप्रमाणित राज्य",
    "alipurduar": "अलीपुरद्वार",
    "ambedkar_nagar": "अंबेडकर नगर",
    "amreli": "अमरेली",
    "angul": "अंगुल",
    "anjaw": "अंज।व",
    "bageshwar": "बागेश्वर",
    "baksa": "बक्सा",
    "balaghat": "बालाघाट",
    "ballia": "बलिया",
    "balod": "बालोद",
    "baloda_bazar": "बलोदा बाजार",
    "bemetara": "बेमेतरा",
    "bankura": "बांकुड़ा",
    "bargarh": "बारगढ़",
    "barpeta": "बारपेटा",
    "bastar": "बस्तर",
    "bijapur": "बीजापुर",
    "bishnupur": "बिश्नुपुर",
    "biswanath": "बिश्वनाथ",
    "boudh": "बौध",
    "bundi": "बूंदी",
    "chamarajanagara": "चामाराजानगर",
    "chamoli": "चमोली",
    "champawat": "चम्पावत",
    "champhai": "चम्फाई",
    "chandauli": "चंदौली",
    "chandel": "चंदेल",
    "changlang": "चांगलांग",
    "charaideo": "चराईदेव",
    "chatra": "चतरा",
    "chhatarpur": "छतरपुर",
    "chikkamagaluru": "चिक्कामगलुरु",
    "chirang": "चिरांग",
    "churachandpur": "छुरछंदपुर",
    "cooch_behar": "कूचबिहार",
    "dakshin_bastar_dantewada": "दक्षिण बस्तर दंतेवाड़ा",
    "dakshin_dinajpur": "दक्षिण दिनाजपुर",
    "daman": "दमन",
    "damoh": "दमोह",
    "darrang": "दरांग",
    "datia": "दतिया",
    "dhamtari": "धमतरी",
    "dhemaji": "धेमाजी",
    "dibrugarh": "डिब्रूगढ़",
    "dima_hasao": "दीमा हसाओ",
    "diu": "दीव",
    "doda": "डोडा",
    "east_garo_hills": "पूर्व गारो हिल्स",
    "east_jaintia_hills": "पूर्व जैंतिया हिल्स",
    "east_kameng": "पूर्वी कामेंग",
    "east_siang": "पूर्व सियांग",
    "east_singhbhum": "पूर्वी सिंहभूम",
    "farrukhabad": "फर्रुखाबाद",
    "gajapati": "गजपति",
    "ganganagar": "गंगानगर",
    "gariaband": "गरियाबंद",
    "gumla": "गुमला",
    "hassan": "हसन",
    "hnahthial": "हनहथीअल",
    "hojai": "होजाइ",
    "jamui": "जमुई",
    "janjgir_champa": "जांजगीर चंपा",
    "jashpur": "जशपुर",
    "jhargram": "झारग्राम",
    "jiribam": "जिरीबाम",
    "jorhat": "जोरहाट",
    "kakching": "कक्चिंग",
    "kamjong": "कमजोंग",
    "kamle": "कमले",
    "kandhamal": "कंधमाल",
    "kangpokpi": "कांगपोकपि",
    "karaikal": "कराईकल",
    "karbi_anglong": "कार्बी आंगलोंग",
    "katni": "कटनी",
    "khawzawl": "खावजॉल",
    "khowai": "खोवाई",
    "khunti": "खूंटी",
    "kinnaur": "किन्नौर",
    "kolar": "कोलार",
    "kolasib": "कोलासिब",
    "kondagaon": "कोंडागांव",
    "koppal": "कोप्पल",
    "koriya": "कोरिया",
    "kra_daadi": "क्रा दादी",
    "kullu": "कुल्लू",
    "kurung_kumey": "कुरुंग कुमे",
    "lahaul_and_spiti": "लाहौल एवं स्पीति",
    "lalitpur": "ललितपुर",
    "latehar": "लातेहार",
    "lawngtlai": "लवंगत्लई",
    "lepa_rada": "लेपा राडा",
    "lohardaga": "लोहरदगा",
    "longding": "लोंगडिंग",
    "lower_dibang_valley": "लोअर दिबांग घाटी",
    "lower_siang": "लोअर सियांग",
    "lower_subansiri": "लोअर सुबानसिरी",
    "lunglei": "लुंगलेई",
    "mahasamund": "महासमुंद",
    "majuli": "माजुली",
    "malkangiri": "मल्कानगिरी",
    "mamit": "मामित",
    "mandla": "मंडला",
    "mirpur": "मीरपुर",
    "mungeli": "मुंगेली",
    "muzaffarabad": "मुजफ्फराबाद",
    "nabarangapur": "नबरंगपुर",
    "nagaon": "नगांव",
    "namsai": "नामसाई",
    "narayanpur": "नारायणपुर",
    "narsinghpur": "नरसिंहपुर",
    "nicobars": "निकोबार",
    "niwari": "निवारी",
    "noney": "नोनी",
    "north_garo_hills": "उत्तर गारो हिल्स",
    "nuapada": "नुआपाड़ा",
    "pakke_kessang": "पक्के केसांग",
    "pakur": "पाकुर",
    "papum_pare": "पापुम पारे",
    "pherzawl": "फरज़ाल",
    "pithoragarh": "पिथोरागढ़",
    "punch": "पंच",
    "purulia": "पुरुलिया",
    "raichur": "रायचुर",
    "raigarh": "रायगढ़",
    "ramanagara": "रामनगर",
    "ramgarh": "रामगढ़",
    "rayagada": "रायगढ़",
    "ribhoi": "रीभोई",
    "rudraprayag": "रुद्रप्रयाग",
    "sahibganj": "साहिबगंज",
    "saiha": "सैहा",
    "saitual": "सैतुअल",
    "sambalpur": "संबलपुर",
    "saraikela-kharsawan": "सराइकेला-खरसावाँ",
    "senapati": "सेनापति",
    "seoni": "सिवनी",
    "serchhip": "सेरछिप",
    "shi_yomi": "शि योमी",
    "shivamogga": "शिवमोगा",
    "siang": "सियांग",
    "sidhi": "सीधी",
    "singrauli": "सिंगरौली",
    "sipahijala": "सिपाहीजाला",
    "sivasagar": "शिवसागर",
    "sonbhadra": "सोनभद्र",
    "sonitpur": "सोनितपुर",
    "south_garo_hills": "दक्षिण गारो हिल्स",
    "south_tripura": "दक्षिण त्रिपुरा",
    "south_west_garo_hills": "दक्षिण पश्चिम गारो हिल्स",
    "south_west_khasi_hills": "साउथ वेस्ट खासी हिल्स",
    "subarnapur": "सुबर्णपुर",
    "sukma": "सुकमा",
    "surguja": "सरगुजा",
    "tamenglong": "तामेंगलांग",
    "tawang": "तवांग",
    "tehri_garhwal": "टिहरी गढ़वाल",
    "tengnoupal": "टेंगनूपाल",
    "thoubal": "थौबल",
    "tinsukia": "तिनसुकिया",
    "tirap": "तिरप",
    "udalguri": "उदलगुड़ी",
    "ukhrul": "उखरूल",
    "umaria": "उमरिया",
    "unokoti": "उनुकोटि",
    "upper_dibang_valley": "ऊपरी दिबांग घाटी",
    "upper_siang": "ऊपरी सियांग",
    "upper_subansiri": "ऊपरी सुबानसिरी",
    "uttar_bastar_kanker": "उत्तर बस्तर कांकेर",
    "uttar_dinajpur": "उत्तर दिनाजपुर",
    "uttarkashi": "उत्तरकाशी",
    "wanaparthy": "वनापर्थी",
    "warangal_rural": "वारंगल ग्रामीण",
    "west_garo_hills": "पश्चिम गारो हिल्स",
    "west_jaintia_hills": "पश्चिम जैंतिया हिल्स",
    "west_kameng": "पश्चिम कामेंग",
    "west_karbi_anglong": "पश्चिम कार्बी आंगलोंग",
    "west_khasi_hills": "पश्चिम खासी हिल्स",
    "west_siang": "पश्चिम सियांग",
    "west_singhbhum": "पश्चिमी सिंहभूम",
    "west_tripura": "पश्चिम त्रिपुरा",
    "yadadri_bhuvanagiri": "यदाद्रि भुवनगिरि",
    "yadgir": "यादगीर",
    "yanam": "यानम",
    "adilabad": "अदिलाबाद",
    "agar_malwa": "आगर मालवा",
    "agra": "आगरा",
    "ahmedabad": "अहमदाबाद",
    "ahmednagar": "अहमदनगर",
    "aizawl": "आइज़ौल",
    "ajmer": "अजमेर",
    "akola": "अकोला",
    "alappuzha": "अलापुझा",
    "aligarh": "अलीगढ़",
    "alirajpur": "अलीराजपुर",
    "almora": "अल्मोड़ा",
    "alwar": "अलवर",
    "ambala": "अंबाला",
    "amethi": "अमेठी",
    "amravati": "अमरावती",
    "amritsar": "अमृतसर",
    "amroha": "अमरोहा",
    "anand": "आनंद",
    "anantapur": "अनंतपुर",
    "anantnag": "अनंतनाग",
    "andhra_pradesh": "आंध्र प्रदेश",
    "anuppur": "अनूपपुर",
    "araria": "अरारिया",
    "aravalli": "अरावली",
    "ariyalur": "अरियालुर",
    "arunachal_pradesh": "अरुणाचल प्रदेश",
    "arwal": "अरवल",
    "ashoknagar": "अशोक नगर",
    "assam": "असम",
    "auraiya": "औरैया",
    "aurangabad": "औरंगाबाद",
    "ayodhya": "अयोध्या",
    "azamgarh": "आज़मगढ़",
    "bagalkote": "बागलकोट",
    "baghpat": "बागपत",
    "bahraich": "बहराइच",
    "balangir": "बोलांगीर",
    "balasore": "बालासोर",
    "ballari": "बेल्लारी",
    "balrampur": "बलरामपुर",
    "banaskantha": "बनासकांठा",
    "banda": "बांदा",
    "bandipora": "बांदीपोरा",
    "banka": "बांका",
    "banswara": "बांसवाड़ा",
    "barabanki": "बाराबंकी",
    "baramulla": "बारामूला",
    "baran": "बारां",
    "bareilly": "बरेली",
    "barmer": "बाड़मेर",
    "barnala": "बरनाला",
    "barwani": "बड़वानी",
    "basti": "बस्ती",
    "bathinda": "भटिंडा",
    "beed": "बीड़",
    "begusarai": "बेगूसराय",
    "belagavi": "बेलगावी",
    "bengaluru_rural": "बेंगलुरु ग्रामीण",
    "bengaluru_urban": "बेंगलुरु शहर",
    "betul": "बैतूल",
    "bhadohi": "भदोही",
    "bhadradri_kothagudem": "भाद्रदरी कोथागुदम",
    "bhadrak": "भद्रक",
    "bhagalpur": "भागलपुर",
    "bhandara": "भण्डारा",
    "bharatpur": "भरतपुर",
    "bharuch": "भरूच",
    "bhavnagar": "भावनगर",
    "bhilwara": "भीलवाड़ा",
    "bhind": "भिंड",
    "bhiwani": "भिवानी",
    "bhojpur": "भोजपुर",
    "bhopal": "भोपाल",
    "bidar": "बीदर",
    "bihar": "बिहार",
    "bijnor": "बिजनौर",
    "bikaner": "बीकानेर",
    "bilaspur": "बिलासपुर",
    "birbhum": "बीरभूम",
    "bokaro": "बोकारो",
    "bongaigaon": "बोंगईगांव",
    "botad": "बोटाद",
    "budaun": "बदायूं",
    "budgam": "बडगाम",
    "bulandshahr": "बुलंदशहर",
    "buldhana": "बुलढाणा",
    "burhanpur": "बुरहानपुर",
    "buxar": "बक्सर",
    "cachar": "कछार",
    "central_delhi": "मध्य दिल्ली",
    "chamba": "चंबा",
    "chandigarh": "चंडीगढ़",
    "chandrapur": "चंद्रपुर",
    "charkhi_dadri": "चरखी दादरी",
    "chengalpattu": "चेंगलपट्टू",
    "chennai": "चेन्नई",
    "chhattisgarh": "छत्तीसगढ़",
    "chhindwara": "छिंदवाड़ा",
    "chhota_udaipur": "छोटा उदयपुर",
    "chikkaballapura": "चिक्कबल्लापुर",
    "chitradurga": "चित्रदुर्ग",
    "chitrakoot": "चित्रकूट",
    "chittoor": "चित्तूर",
    "chittorgarh": "चित्तौड़गढ़",
    "churu": "चुरू",
    "coimbatore": "कोयंबटूर",
    "cuddalore": "कुड्डालोर",
    "cuttack": "कटक",
    "dadra_and_nagar_haveli": "दादरा और नगर हवेली",
    "dadra_and_nagar_haveli_and_daman_and_diu": "दादरा और नगर हवेली तथा दमन और दीव",
    "dahod": "दाहोद",
    "dakshina_kannada": "दक्षिण कन्नड़",
    "daman_and_diu": "दमन और दीव",
    "dang": "डांग",
    "darbhanga": "दरभंगा",
    "darjeeling": "दार्जिलिंग",
    "dausa": "दौसा",
    "davanagere": "दावण गेरे",
    "dehradun": "देहरादून",
    "delhi": "दिल्ली",
    "deogarh": "देवगढ़",
    "deoghar": "देवघर",
    "deoria": "देओरिया",
    "devbhumi_dwarka": "देवभूमि द्वारका",
    "dewas": "देवास",
    "dhalai": "ढलाई",
    "dhanbad": "धनबाद",
    "dhar": "धार",
    "dharmapuri": "धर्मपुरी",
    "dharwad": "धारवाड़",
    "dhenkanal": "ढेंकनाल",
    "dholpur": "धौलपुर",
    "dhubri": "धुबरी",
    "dhule": "धूले",
    "dindigul": "डिंडीगुल",
    "dindori": "डिंडोरी",
    "dumka": "दुमका",
    "dungarpur": "डूंगरपुर",
    "durg": "दुर्ग",
    "east_champaran": "पूर्वी चंपारण",
    "east_delhi": "पूर्वी दिल्ली",
    "east_godavari": "पूर्वी गोदावरी",
    "east_khasi_hills": "पूर्वी खासी हिल्स",
    "ernakulam": "एर्नाकुलम",
    "erode": "इरोड",
    "etah": "ईटाह",
    "etawah": "इटावा",
    "faridabad": "फ़रीदाबाद",
    "faridkot": "फरीदकोट",
    "fatehabad": "फतेहाबाद",
    "fatehgarh_sahib": "फतेहगढ़ साहिब",
    "fatehpur": "फतेहपुर",
    "fazilka": "फजिल्का",
    "ferozepur": "फिरोज़पुर",
    "firozabad": "फ़िरोज़ाबाद",
    "gadag": "गदग",
    "gadchiroli": "गढ़चिरोली",
    "ganderbal": "गंदएरबल",
    "gandhinagar": "गांधीनगर",
    "ganjam": "गंजाम",
    "garhwa": "गढ़वा",
    "gaurela_pendra_marwahi": "गौरेला पेंड्रा मरवाही",
    "gautam_buddha_nagar": "गौतम बुद्ध नगर",
    "gaya": "गया",
    "ghaziabad": "गाज़ियाबाद",
    "ghazipur": "गाज़ीपुर",
    "gir_somnath": "गीर सोमनाथ",
    "giridih": "गिरिडीह",
    "goa": "गोवा",
    "goalpara": "गोलपाड़ा",
    "godda": "गोड्डा",
    "golaghat": "गोलाघाट",
    "gomati": "गोमती",
    "gonda": "गोंडा",
    "gondia": "गोंदिया",
    "gopalganj": "गोपालगंज",
    "gorakhpur": "गोरखपुर",
    "gujarat": "गुजरात",
    "guna": "गुना",
    "guntur": "गुंटूर",
    "gurdaspur": "गुरदासपुर",
    "gurugram": "गुरुग्राम",
    "gwalior": "ग्वालियर",
    "hailakandi": "हैलाकांडी",
    "hamirpur": "हमीरपुर",
    "hanumangarh": "हनुमानगढ़",
    "hapur": "हापुड़",
    "harda": "हरदा",
    "hardoi": "हरदोई",
    "haridwar": "हरिद्वार",
    "haryana": "हरियाणा",
    "hathras": "हाथरस",
    "haveri": "हावेरी",
    "hazaribagh": "हज़ारीबाग",
    "himachal_pradesh": "हिमाचल प्रदेश",
    "hingoli": "हिंगोली",
    "hisar": "हिसार",
    "hooghly": "हुगली",
    "hoshangabad": "होशंगाबाद",
    "hoshiarpur": "होशियारपुर",
    "howrah": "हावड़ा",
    "hyderabad": "हैदराबाद",
    "idukki": "इडुक्की",
    "imphal_east": "इम्फाल पूर्व",
    "imphal_west": "इम्फाल पश्चिम",
    "indore": "इंदौर",
    "jabalpur": "जबलपुर",
    "jagatsinghpur": "जगतसिंहपुर",
    "jagtial": "जग्तियाल",
    "jaipur": "जयपुर",
    "jaisalmer": "जैसलमेर",
    "jajpur": "जाजपुर",
    "jalandhar": "जालंधर",
    "jalaun": "जालौन",
    "jalgaon": "जलगांव",
    "jalna": "जालना",
    "jalore": "जालोर",
    "jalpaiguri": "जलपाईगुड़ी",
    "jammu": "जम्मू",
    "jammu_and_kashmir": "जम्मू-कश्मीर",
    "jammu_&_kashmir": "जम्मू और कश्मीर",
    "jamnagar": "जामनगर",
    "jamtara": "जामतारा",
    "jangaon": "जनगांव",
    "jaunpur": "जौनपुर",
    "jayashankar_bhupalapally": "जयशंकर भुपालपल्ली",
    "jehanabad": "जेहांनाबाद",
    "jhabua": "झाबुआ",
    "jhajjar": "झज्जर",
    "jhalawar": "झालावाड़",
    "jhansi": "झाँसी",
    "jharkhand": "झारखंड",
    "jharsuguda": "झारसुगुड़ा",
    "jhunjhunu": "झुंझुनूं",
    "jind": "जिंद ",
    "jodhpur": "जोधपुर",
    "jogulamba_gadwal": "जोगुलाम्बा गढ़वाल",
    "junagadh": "जूनागढ़",
    "kabeerdham": "कबीरधाम",
    "kaimur": "कैमूर",
    "kaithal": "कैथल",
    "kalaburagi": "कालाबुर्गी",
    "kalahandi": "कलाहंडी",
    "kalimpong": "कालिमपोंग",
    "kallakurichi": "कल्लाकुरिची",
    "kamareddy": "कामारेड्डी",
    "kamrup": "कामरूप",
    "kamrup_metropolitan": "कामरूप महानगर",
    "kancheepuram": "कांचीपुरम",
    "kangra": "कांगड़ा",
    "kannauj": "कन्नौज",
    "kannur": "कन्नूर",
    "kanpur_dehat": "कानपुर देहात",
    "kanpur_nagar": "कानपुर नगर",
    "kanyakumari": "कन्याकुमारी",
    "kapurthala": "कपूरथला",
    "karauli": "करौली",
    "kargil": "कारगिल",
    "karimganj": "करीमगंज",
    "karimnagar": "करीमनगर",
    "karnal": "करनाल",
    "karnataka": "कर्नाटक",
    "karur": "करूर",
    "kasaragod": "कासरगोड",
    "kasganj": "कासगंज",
    "kathua": "कठुआ",
    "katihar": "कटिहार",
    "kaushambi": "कौशाम्बी",
    "kendrapara": "केंद्रापाड़ा",
    "kendujhar": "केंदुझार",
    "kerala": "केरल",
    "khagaria": "खगड़िया",
    "khammam": "खम्माम",
    "khandwa": "खंडवा",
    "khargone": "खरगोन",
    "kheda": "खेड़ा",
    "khordha": "खोरधा",
    "kishanganj": "किशनगंज",
    "kishtwar": "किश्तवार",
    "kodagu": "कोडागू",
    "koderma": "कोडरमा",
    "kokrajhar": "कोकराझार",
    "kolhapur": "कोल्हापुर",
    "kolkata": "कोलकाता",
    "kollam": "कोल्लम",
    "komaram_bheem": "कोमाराम भीम",
    "koraput": "कोरापुट",
    "korba": "कोरबा",
    "kota": "कोटा",
    "kottayam": "कोट्टायम",
    "kozhikode": "कोझिकोड",
    "krishna": "कृष्णा",
    "krishnagiri": "कृष्णागिरी",
    "kulgam": "कुलगाम",
    "kupwara": "कुपवाड़ा",
    "kurnool": "कुरनूल",
    "kurukshetra": "कुरुक्षेत्र",
    "kushinagar": "कुशीनगर",
    "kutch": "कच्छ",
    "ladakh": "लद्दाख",
    "lakhimpur": "लखीमपुर",
    "lakhimpur_kheri": "लखीमपुर खीरी",
    "lakhisarai": "लखीसराय",
    "lakshadweep": "लक्षद्वीप",
    "latur": "लातूर",
    "leh": "लेह",
    "lohit": "लोहित",
    "lucknow": "लखनऊ",
    "ludhiana": "लुधियाना",
    "madhepura": "मधेपुरा",
    "madhubani": "मधुबनी",
    "madhya_pradesh": "मध्य प्रदेश",
    "madurai": "मदुरै",
    "mahabubabad": "मह्बुबाबाद",
    "mahabubnagar": "महबूबनगर",
    "maharajganj": "महाराजगंज",
    "maharashtra": "महाराष्ट्र",
    "mahe": "माहे",
    "mahendragarh": "महेंद्रगढ़",
    "mahisagar": "महिसागर",
    "mahoba": "महोबा",
    "mainpuri": "मैनपुरी",
    "malappuram": "मालाप्पुरम",
    "malda": "मालदा",
    "mancherial": "मंचेरियाल",
    "mandi": "मंडी",
    "mandsaur": "मंदसौर",
    "mandya": "मंड्या",
    "manipur": "मणीपुर",
    "mansa": "मानसा",
    "mathura": "मथुरा",
    "mau": "महू",
    "mayurbhanj": "मयूरभंज",
    "medak": "मेदक",
    "medchal_malkajgiri": "मेडचाल मल्काजगिरी",
    "meerut": "मेरठ",
    "meghalaya": "मेघालय",
    "mehsana": "मेहसाणा",
    "mirzapur": "मिर्ज़ापुर",
    "mizoram": "मिज़ोरम",
    "moga": "मोगा",
    "moradabad": "मुरादाबाद",
    "morbi": "मोरबी",
    "morena": "मुरैना",
    "morigaon": "मोरीगांव",
    "mulugu": "मुलुगु",
    "mumbai": "मुंबई",
    "mumbai_suburban": "मुंबई उपनगरीय",
    "munger": "मुंगेर",
    "murshidabad": "मुर्शिदाबाद",
    "muzaffarnagar": "मुज़फ्फरनगर",
    "muzaffarpur": "मुज़फ्फरपुर",
    "mysuru": "मैसूर",
    "nadia": "नादिया",
    "nagaland": "नागालैंड",
    "nagapattinam": "नागपट्टिनम",
    "nagarkurnool": "नगरकुरनूल",
    "nagaur": "नागौर",
    "nagpur": "नागपुर",
    "nainital": "नैनीताल",
    "nalanda": "नालंदा",
    "nalbari": "नलबाड़ी",
    "nalgonda": "नालगोंडा",
    "namakkal": "नमक्कल",
    "nanded": "नांदेड़",
    "nandurbar": "नंदुरबार",
    "narayanpet": "नारायणपेट",
    "narmada": "नर्मदा",
    "nashik": "नासिक",
    "navsari": "नवसारी",
    "nawada": "नवादा",
    "nayagarh": "नयागढ़",
    "neemuch": "नीमच",
    "new_delhi": "नई दिल्ली",
    "nilgiris": "नीलगिरी",
    "nirmal": "निर्मल",
    "nizamabad": "निज़ामाबाद",
    "north_24_parganas": "उत्तर 24 परगना",
    "north_and_middle_andaman": "उत्तर और मध्य अंदमान",
    "north_delhi": "उत्तरी दिल्ली",
    "north_east_delhi": "उत्तर पूर्व दिल्ली",
    "north_goa": "उत्तरी गोवा",
    "north_tripura": "उत्तरी त्रिपुरा",
    "north_west_delhi": "उत्तर पश्चिम दिल्ली",
    "nuh": "नूह",
    "odisha": "ओडिशा",
    "osmanabad": "उस्मानाबाद",
    "palakkad": "पलक्कड़",
    "palamu": "पलामु",
    "palghar": "पालघर",
    "pali": "पाली",
    "palwal": "पलवल",
    "panchkula": "पंचकुला",
    "panchmahal": "पंचमहल",
    "panipat": "पानीपत",
    "panna": "पन्ना",
    "parbhani": "परभनी",
    "paschim_bardhaman": "पश्चिम वर्धमानन",
    "paschim_medinipur": "पश्चिम मेदिनीपुर",
    "patan": "पाटन",
    "pathanamthitta": "पथानमथिट्टा",
    "pathankot": "पठानकोट",
    "patiala": "पटियाला",
    "patna": "पटना",
    "pauri_garhwal": "पौड़ी गढ़वाल",
    "peddapalli": "पेद्दापल्ली",
    "perambalur": "पेराम्बलुर",
    "pilibhit": "पीलीभीत",
    "porbandar": "पोरबंदर",
    "prakasam": "प्रकाशम",
    "pratapgarh": "प्रतापगढ़",
    "prayagraj": "प्रयागराज",
    "puducherry": "पुदुच्चेरी",
    "pudukkottai": "पुदुक्कोट्टई",
    "pulwama": "पुलवामा",
    "pune": "पुणे",
    "punjab": "पंजाब",
    "purba_bardhaman": "पूर्व वर्धमान",
    "purba_medinipur": "पूर्व मेदिनीपुर",
    "puri": "पुरी",
    "purnia": "पूर्णिया",
    "rae_bareli": "रायबरेली",
    "raigad": "रायगढ़",
    "raipur": "रायपुर",
    "raisen": "रायसेन",
    "rajanna_sircilla": "राजन्ना सिरसिल्ला",
    "rajasthan": "राजस्थान",
    "rajgarh": "राजगढ़",
    "rajkot": "राजकोट",
    "rajnandgaon": "राजनंदगाव",
    "rajouri": "राजौरी",
    "rajsamand": "राजसमंद",
    "ramanathapuram": "रामनाथपुरम",
    "ramban": "रामबाण",
    "rampur": "रामपुर",
    "ranchi": "रांची",
    "ranga_reddy": "रंगा रेड्डी",
    "ranipet": "रानीपेट",
    "ratlam": "रतलाम",
    "ratnagiri": "रत्नागिरी",
    "reasi": "रियासी",
    "rewa": "रीवा",
    "rewari": "रेवाड़ी",
    "rohtak": "रोहतक",
    "rohtas": "रोहतास",
    "rupnagar": "रूपनगर",
    "s.a.s._nagar": "एस.ए.एस. नगर",
    "s.p.s._nellore": "एस० पी० एस० नेल्लोर",
    "shahid_bhagat_singh_nagar": "शहीद भगत सिंह नगर",
    "sabarkantha": "साबरकांठा",
    "sagar": "सागर",
    "saharanpur": "सहारनपुर",
    "saharsa": "सहरसा",
    "salem": "सलेम",
    "samastipur": "समस्तीपुर",
    "samba": "साम्बा",
    "sambhal": "संभल",
    "sangareddy": "संगारेड्डी",
    "sangli": "सांगली",
    "sangrur": "संगरूर",
    "sant_kabir_nagar": "संत कबीर नगर",
    "saran": "सारण",
    "satara": "सातारा",
    "satna": "सतना",
    "sawai_madhopur": "सवाई माधोपुर",
    "sehore": "सीहोर",
    "shahdara": "शाहदरा",
    "shahdol": "शहडोल",
    "shahjahanpur": "शाहजहांपुर",
    "shajapur": "शाजापुर",
    "shamli": "शामली",
    "sheikhpura": "शेखपुरा",
    "sheohar": "शिवहर",
    "sheopur": "श्योपुर",
    "shimla": "शिमला",
    "shivpuri": "शिवपुरी",
    "shopiyan": "शोपियां",
    "shrawasti": "श्रावस्ती",
    "siddharthnagar": "सिद्धार्थनगर",
    "siddipet": "सिद्दीपेट",
    "sikar": "सीकर",
    "sikkim": "सिक्किम",
    "north_sikkim": "उत्तर सिक्किम",
    "south_sikkim": "दक्षिण सिक्किम",
    "east_sikkim": "पूर्वी सिक्किम",
    "west_sikkim": "पश्चिम सिक्किम",
    "simdega": "सिमडेगा",
    "sindhudurg": "सिंधुदुर्ग",
    "sirmaur": "सिरमौर",
    "sirohi": "सिरोही",
    "sirsa": "सिरसा",
    "sitamarhi": "सीतामढ़ी",
    "sitapur": "सीतापुर",
    "sivaganga": "शिवगंगा",
    "siwan": "सिवान",
    "solan": "सोलन",
    "solapur": "सोलापुर",
    "sonipat": "सोनीपत",
    "south_24_parganas": "दक्षिण 24 परगना",
    "andaman_and_nicobar_islands": "अंडमान व नोकोबार द्वीप समूह",
    "south_andaman": "दक्षिणी अंदमान",
    "south_delhi": "दक्षिण दिल्ली",
    "south_east_delhi": "दक्षिण पूर्व दिल्ली",
    "south_goa": "दक्षिणी गोवा",
    "south_salmara_mankachar": "दक्षिण सल्मारा मन्काचर",
    "south_west_delhi": "दक्षिण पश्चिम दिल्ली",
    "sri_muktsar_sahib": "श्री मुक्तसर साहिब",
    "srikakulam": "श्रीकाकुलम",
    "srinagar": "श्रीनगर",
    "sultanpur": "सुल्तानपुर",
    "sundargarh": "सुंदरगढ़",
    "supaul": "सुपौल",
    "surajpur": "सुरजपुर",
    "surat": "सूरत",
    "surendranagar": "सुरेंद्रनगर",
    "suryapet": "सूर्यपेट",
    "tamil_nadu": "तमिलनाडु",
    "tapi": " तापी",
    "tarn_taran": "तरन तारन",
    "telangana": "तेलंगाना",
    "tenkasi": "तेनकासी",
    "thane": "ठाणे",
    "thanjavur": "थांजावुर",
    "theni": "थेनी",
    "thiruvallur": "तिरुवल्लुर",
    "thiruvananthapuram": "तिरुवनंथपुरम",
    "thiruvarur": "थिरुवरुर",
    "thoothukkudi": "थूथुकुडी",
    "thrissur": "थ्रिसुर",
    "tikamgarh": "टीकमगढ़",
    "tiruchirappalli": "तिरुचिरापल्ली",
    "tirunelveli": "तिरुनेलवेली",
    "tirupathur": "तिरुपथु",
    "tiruppur": "तिरुपूर",
    "tiruvannamalai": "तिरुवन्नामलाई",
    "tonk": "टोंक",
    "tripura": "त्रिपुरा",
    "tumakuru": "तुमकुरु",
    "udaipur": "उदयपुर",
    "udham_singh_nagar": "उधम सिंह नगर",
    "udhampur": "उधमपुर",
    "udupi": "उडुपी",
    "ujjain": "उज्जैन",
    "una": "ऊना",
    "unnao": "उन्नाव",
    "uttar_pradesh": "उत्तर प्रदेश",
    "uttara_kannada": "उत्तर कन्नड़",
    "uttarakhand": "उत्तराखंड",
    "vadodara": "वड़ोदरा",
    "vaishali": "वैशाली",
    "valsad": "वलसाड़",
    "varanasi": "वाराणसी",
    "vellore": "वेल्लोर",
    "vidisha": "विदिशा",
    "vijayapura": "विजयपुरा",
    "vikarabad": "विकाराबाद",
    "viluppuram": "विलुप्पुरम",
    "virudhunagar": "विरुधुनगर",
    "visakhapatnam": "विशाखापत्तनम",
    "vizianagaram": "विजयनगरम",
    "warangal_urban": "वारंगल शहरी",
    "wardha": "वर्धा",
    "washim": "वाशिम",
    "wayanad": "वायनाड",
    "west_bengal": "पश्चिम बंगाल",
    "west_champaran": "पश्चिमी चंपारण",
    "west_delhi": "पश्चिमी दिल्ली",
    "west_godavari": "पश्चिमी गोदावरी",
    "y.s.r._kadapa": "YSR कड़पा",
    "yamunanagar": "यमुनानगर",
    "yavatmal": "यवतमाल",
    "bametara": "बेमेतरा"
}

countries_hi = {
    "diamond_princess": "* डायमंड प्रिंसेस",
    "ms_zaandam": "* एम.एस. जानदाम",
    "afghanistan": "अफ़ग़ानिस्तान",
    "albania": "अल्बानिया",
    "algeria": "एलजीरिया",
    "american_samoa": "अमेरिकन समोआ",
    "andorra": "अंडोरा",
    "angola": "अंगोला",
    "anguilla": "एंगुइला",
    "antarctica": "अंटार्कटिका",
    "antigua_and_barbuda": "अंतिगुया और बार्बूडा",
    "argentina": "अर्जेंटीना",
    "armenia": "आर्मीनिया",
    "aruba": "अरूबा",
    "australia": "ऑस्ट्रेलिया",
    "austria": "ऑस्ट्रिया",
    "azerbaijan": "आज़रबाइजान",
    "bahamas": "बहामा",
    "bahrain": "बहरीन",
    "bangladesh": "बांग्लादेश",
    "barbados": "बारबाडोस",
    "belarus": "बेलोरूस",
    "belgium": "बेल्जियम",
    "belize": "बेलीज",
    "benin": "बेनिन",
    "bermuda": "बरमूडा",
    "bhutan": "भूटान",
    "bolivia": "बोलीविया",
    "bosnia_and_herzegovina": "बोस्निया और हर्जेगोविना",
    "bosnia": "बोस्निया",
    "botswana": "बोत्सवाना",
    "bouvet_island": "बौवेट आइलैंड",
    "brazil": "ब्राज़िल",
    "british_indian_ocean_territory": "ब्रिटिश हिंद महासागर क्षेत्र",
    "british_virgin_islands": "ब्रिटिश वर्जिन आईलैन्ड्स",
    "brunei": "ब्रुनेई",
    "bulgaria": "बुल्गारिया",
    "burkina_faso": "बुर्किना फासो",
    "burundi": "बुस्र्न्दी",
    "cambodia": "कंबोडिया",
    "cameroon": "कैमरून",
    "canada": "कनाडा",
    "cape_verde": "केप वर्दे",
    "caribbean_netherlands": "कैरेबियन नीदरलैंड",
    "cayman_islands": "केमैन टापू",
    "central_african_republic": "केंद्रीय अफ्रीकन रिपब्लिक",
    "chad": "चाड",
    "chile": "चिली",
    "china": "चीन",
    "channel_islands": "खाड़ी द्वीप",
    "christmas_island": "क्रिसमस द्वीप",
    "cabo_verde": "काबो वर्डे",
    "cocos_(keeling)_islands": "कोकोस (कीलिंग) द्वीप समूह",
    "cocos_islands": "कोकोस द्वीप समूह",
    "keeling": "कीलिंग",
    "keeling_islands": "कीलिंग द्वीप समूह",
    "colombia": "कोलम्बिया",
    "comoros": "कोमोरोस",
    "congo": "कांगो",
    "the_democratic_republic_of_congo": "कांगो लोकतांत्रिक रिपब्लिक",
    "cook_islands": "कुक द्वीपसमूह",
    "costa_rica": "कोस्टा रिका",
    "côte_d'ivoire": "कोटे डी आइवर",
    "curaçao": "कुराकाओ",
    "ivory_coast": "आईवरी कोस्ट",
    "croatia": "क्रोएशिया",
    "cuba": "क्यूबा",
    "cyprus": "साइप्रस",
    "czech_republic": "चेक रिपब्लिक",
    "czechia": "ज़ेकिया",
    "denmark": "डेनमार्क",
    "djibouti": "जिबूती",
    "dominica": "डोमिनिका",
    "dominican_republic": "डोमिनिकन रिपब्लिक",
    "drc": "डी.आर.सी",
    "east_timor": "पूर्वी तिमोर",
    "ecuador": "इक्वेडोर",
    "egypt": "मिस्र",
    "england": "England",
    "el_salvador": "एल साल्वाडोर",
    "equatorial_guinea": "इक्वेटोरियल गिनी",
    "eritrea": "इरिट्रिया",
    "estonia": "एस्तोनिया",
    "ethiopia": "इथियोपिया",
    "falkland_islands": "फ़ॉकलैंड आइलैंड",
    "falkland_islands_(malvinas)": "फ़ॉकलैंड आइलैंड (माल्विनास)",
    "malvinas": "माल्विनास",
    "malvinas_island": "माल्विनास आइलैंड",
    "faroe_islands": "फ़ैरो द्वीप",
    "fiji_islands": "फिजी द्वीप समूह",
    "fiji": "फ़िजी",
    "finland": "फिनलैंड",
    "france": "फ्रांस",
    "french_guiana": "फ्रेंच गयाना",
    "french_polynesia": "फ्रेंच पॉलीनेशिया",
    "french_southern_territories": "दक्षिणी फ्राँसिसी क्षेत्र",
    "gabon": "गैबॉन",
    "gambia": "गाम्बिया",
    "georgia": "जॉर्जिया",
    "germany": "जर्मनी",
    "ghana": "घाना",
    "gibraltar": "जिब्राल्टर",
    "greece": "यूनान",
    "greenland": "ग्रीनलैंड",
    "grenada": "ग्रेनेडा",
    "guadeloupe": "ग्वाडेलोप",
    "guam": "गुआम",
    "guatemala": "ग्वाटेमाला",
    "guernsey": "ग्वेर्नसे",
    "guinea": "गिन्नी",
    "guinea-bissau": "गिनी-बिसाऊ",
    "guyana": "गुयाना",
    "haiti": "हाईटि",
    "heard_island_and_mcdonald_islands": "हर्ड आइलैंड और मैकडोनाल्ड आइलैंड्स",
    "holy_see_(vatican_city_state)": "होली सी (वेटिकन सिटी स्टेट)",
    "honduras": "होंडुरस",
    "hong_kong": "हाँग काँग",
    "hungary": "हंगरी",
    "iceland": "आइसलैंड",
    "india": "भारत",
    "indonesia": "इंडोनेशिया",
    "iran": "ईरान",
    "iraq": "इराक",
    "ireland": "आयरलैंड",
    "israel": "इजराइल",
    "isle_of_man": "मैन द्वीप",
    "italy": "इटली",
    "jamaica": "जमैका",
    "japan": "जापान",
    "jersey": "जर्सी",
    "jordan": "जॉर्डन",
    "kazakhstan": "कज़ाकस्तान",
    "kenya": "केन्या",
    "kiribati": "किरिबाती",
    "kuwait": "कुवैत",
    "kyrgyzstan": "किर्गिज़स्तान",
    "lao_people's_democratic_republic": "लाओ पीपुल्स डेमोक्रेटिक रिपब्लिक",
    "laos": "लाओस",
    "latvia": "लातविया",
    "lebanon": "लेबनान",
    "lesotho": "लिसोटो",
    "liberia": "लाइबेरिया",
    "libyan_arab_jamahiriya": "लीबिया का अरब जमहिरिया",
    "liechtenstein": "लिचेंस्टीन",
    "lithuania": "लिथुआनिया",
    "luxembourg": "लक्समबर्ग",
    "macao": "मकाओ",
    "north_macedonia": "उत्तर मैसेडोनिया",
    "macedonia": "मैसेडोनिया",
    "madagascar": "मेडागास्कर",
    "malawi": "मलावी",
    "malaysia": "मलेशिया",
    "maldives": "मालदीव",
    "mali": "माली",
    "malta": "माल्टा",
    "marshall_islands": "मार्शल द्वीप समूह",
    "martinique": "मार्टीनिक",
    "mauritania": "मॉरिटानिया",
    "mauritius": "मॉरीशस",
    "mayotte": "मायोटी",
    "mexico": "मेक्सिको",
    "micronesia,_federated_states_of": "माइक्रोनेशिया, संघीय राज्य",
    "moldova": "मोलदोवा",
    "monaco": "मोनाको",
    "mongolia": "मंगोलिया",
    "montenegro": "मोंटेनेग्रो",
    "montserrat": "मोंटेसेराट",
    "morocco": "मोरक्को",
    "mozambique": "मोजाम्बिक",
    "myanmar": "म्यांमार",
    "namibia": "नामीबिया",
    "nauru": "नाउरू",
    "nepal": "नेपाल",
    "netherlands": "नीदरलैंड",
    "netherlands_antilles": "नीदरलैंड्स एंटाइल्स",
    "new_caledonia": "न्यू कैलेडोनिया",
    "new_zealand": "न्यूजीलैंड",
    "nicaragua": "निकारागुआ",
    "niger": "नाइजर",
    "nigeria": "नाइजीरिया",
    "niue": "नियू",
    "norfolk_island": "नॉरफ़ॉक आइलैंड",
    "north_korea": "उत्तर कोरिया",
    "n._korea": "उत्तर कोरिया",
    "northern_ireland": "उत्तरी आयरलैंड",
    "northern_mariana_islands": "उत्तरी मरीयाना द्वीप समूह",
    "norway": "नॉर्वे",
    "oman": "ओमान",
    "pakistan": "पाकिस्तान",
    "palau": "पलाऊ",
    "palestine": "पलेस्टाइन",
    "panama": "पनामा",
    "papua_new_guinea": "पापुआ न्यू गिनी",
    "paraguay": "परागुआ",
    "peru": "पेरू",
    "philippines": "फिलीपींस",
    "pitcairn": "पिटकेर्न",
    "poland": "पोलैंड",
    "portugal": "पुर्तगाल",
    "puerto_rico": "प्यूर्टो रिको",
    "qatar": "कतर",
    "reunion": "रीयूनियन",
    "réunion": "रियूनियन",
    "romania": "रोमानिया",
    "russian_federation": "रूसी संघ",
    "russia": "रूस",
    "rwanda": "रवांडा",
    "st._barth": "सेंट बार्थ",
    "saint_martin": "सेंट मार्टिन",
    "saint_helena": "सेंट हेलेना",
    "saint_kitts_and_nevis": "सैंत किट्स एंड नेविस",
    "saint_lucia": "सेंट लूसिया",
    "saint_pierre_and_miquelon": "सेंट पियरे और मिकेलॉन",
    "saint_pierre_miquelon": "सेंट पियरे मिकेलॉन",
    "saint_vincent_and_the_grenadines": "सेंट विंसेंट अँड थे ग्रेनडीनेस",
    "samoa": "समोआ",
    "san_marino": "सैन मैरीनो",
    "sao_tome_and_principe": "साओ टोमे और प्रिंसिपे",
    "saudi_arabia": "सऊदी अरब",
    "scotland": "स्कॉटलैंड",
    "senegal": "सेनेगल",
    "serbia": "सर्बिया",
    "seychelles": "सेशेल्स",
    "sierra_leone": "सियरा लिओन",
    "singapore": "सिंगापुर",
    "sint_maarten": "सिंट मार्टेन",
    "slovakia": "स्लोवाकिया",
    "slovenia": "स्लोवेनिया",
    "solomon_islands": "सोलोमन इस्लैंडस",
    "somalia": "सोमालिया",
    "south_africa": "दक्षिण अफ्रीका",
    "south_georgia_and_the_south_sandwich_islands": "दक्षिण जॉर्जिया और दक्षिण सैंडविच द्वीप समूह",
    "south_korea": "दक्षिण कोरिया",
    "s._korea": "दक्षिण कोरिया",
    "south_sudan": "दक्षिण सूडान",
    "spain": "स्पेन",
    "sri_lanka": "श्री लंका",
    "sudan": "सूडान",
    "suriname": "सूरीनाम",
    "svalbard_and_jan_mayen": "स्वालबार्ड और जान मेयन",
    "swaziland": "स्वाजीलैंड",
    "sweden": "स्वीडन",
    "switzerland": "स्विट्जरलैंड",
    "syria": "सीरिया",
    "syrian_arab_republic": "सीरियाई अरब गणराज्य",
    "taiwan": "ताइवान",
    "tajikistan": "तजाकिस्तान",
    "tanzania": "तंजानिया",
    "thailand": "थाईलैंड",
    "timor-leste": "तिमोर-लेस्ते",
    "togo": "टोगो",
    "tokelau": "टोकेलाऊ",
    "tonga": "टोंगा",
    "trinidad_and_tobago": "त्रिनिदाद और टोबैगो",
    "tunisia": "ट्यूनीशिया",
    "turkey": "तुर्की",
    "turkmenistan": "तुर्कमेनिस्तान",
    "turks_and_caicos_islands": "तुर्क्स और कैकोज़ द्वीपसमूह",
    "tuvalu": "तुवालु",
    "uganda": "युगांडा",
    "ukraine": "यूक्रेन",
    "united_arab_emirates": "संयुक्त अरब अमीरात",
    "uae": "संयुक्त अरब अमीरात",
    "united_kingdom": "यूनाइटेड किंगडम",
    "uk": "यू.के.",
    "united_states": "संयुक्त राज्य अमेरिका",
    "united_states_of_america": "संयुक्त राज्य अमेरिका",
    "usa": "यू.एस.ए.",
    "united_states_minor_outlying_islands": "संयुक्त राज्य अमेरिका के छोटे दूरस्थ द्वीपसमूह",
    "uruguay": "उरुग्वे",
    "uzbekistan": "उज़्बेकिस्तान",
    "vanuatu": "वानुअतु",
    "venezuela": "वेनेजुएला",
    "vietnam": "वियतनाम",
    "virgin_islands,_british": "वर्जिन द्वीप समूह, ब्रिटिश",
    "virgin_islands,_u.s.": "वर्जिन द्वीप समूह, यू.एस.वर्जिन द्वीप समूह, यू.एस.ए.",
    "wales": "वेल्स",
    "wallis_and_futuna": "वाली और फ़्युटुना",
    "western_sahara": "पश्चिमी सहारा",
    "yemen": "यमन",
    "yugoslavia": "यूगोस्लाविया",
    "zambia": "जाम्बिया",
    "zimbabwe": "जिम्बाब्वे"